/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Fermyon.Nomad.Client;
using Fermyon.Nomad.Api;
// uncomment below to import models
//using Fermyon.Nomad.Model;

namespace Fermyon.Nomad.Test.Api
{
    /// <summary>
    ///  Class for testing ClientsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ClientsApiTests : IDisposable
    {
        private ClientsApi instance;

        public ClientsApiTests()
        {
            instance = new ClientsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClientsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ClientsApi
            //Assert.IsType<ClientsApi>(instance);
        }

        /// <summary>
        /// Test GetAllocationLogs
        /// </summary>
        [Fact]
        public void GetAllocationLogsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string task = null;
            //string type = null;
            //string allocID = null;
            //bool? follow = null;
            //int? offset = null;
            //string origin = null;
            //bool? plain = null;
            //var response = instance.GetAllocationLogs(task, type, allocID, follow, offset, origin, plain);
            //Assert.IsType<AllocationLogs>(response);
        }
    }
}
