/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Fermyon.Nomad.Client;
using Fermyon.Nomad.Api;
// uncomment below to import models
//using Fermyon.Nomad.Model;

namespace Fermyon.Nomad.Test.Api
{
    /// <summary>
    ///  Class for testing NodesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class NodesApiTests : IDisposable
    {
        private NodesApi instance;

        public NodesApiTests()
        {
            instance = new NodesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NodesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' NodesApi
            //Assert.IsType<NodesApi>(instance);
        }

        /// <summary>
        /// Test GetNode
        /// </summary>
        [Fact]
        public void GetNodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string nodeId = null;
            //string? region = null;
            //string? varNamespace = null;
            //int? index = null;
            //string? wait = null;
            //string? stale = null;
            //string? prefix = null;
            //string? xNomadToken = null;
            //int? perPage = null;
            //string? nextToken = null;
            //var response = instance.GetNode(nodeId, region, varNamespace, index, wait, stale, prefix, xNomadToken, perPage, nextToken);
            //Assert.IsType<Node>(response);
        }

        /// <summary>
        /// Test GetNodeAllocations
        /// </summary>
        [Fact]
        public void GetNodeAllocationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string nodeId = null;
            //string? region = null;
            //string? varNamespace = null;
            //int? index = null;
            //string? wait = null;
            //string? stale = null;
            //string? prefix = null;
            //string? xNomadToken = null;
            //int? perPage = null;
            //string? nextToken = null;
            //var response = instance.GetNodeAllocations(nodeId, region, varNamespace, index, wait, stale, prefix, xNomadToken, perPage, nextToken);
            //Assert.IsType<List<AllocationListStub>>(response);
        }

        /// <summary>
        /// Test GetNodes
        /// </summary>
        [Fact]
        public void GetNodesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? region = null;
            //string? varNamespace = null;
            //int? index = null;
            //string? wait = null;
            //string? stale = null;
            //string? prefix = null;
            //string? xNomadToken = null;
            //int? perPage = null;
            //string? nextToken = null;
            //bool? resources = null;
            //var response = instance.GetNodes(region, varNamespace, index, wait, stale, prefix, xNomadToken, perPage, nextToken, resources);
            //Assert.IsType<List<NodeListStub>>(response);
        }

        /// <summary>
        /// Test UpdateNodeDrain
        /// </summary>
        [Fact]
        public void UpdateNodeDrainTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string nodeId = null;
            //NodeUpdateDrainRequest nodeUpdateDrainRequest = null;
            //string? region = null;
            //string? varNamespace = null;
            //int? index = null;
            //string? wait = null;
            //string? stale = null;
            //string? prefix = null;
            //string? xNomadToken = null;
            //int? perPage = null;
            //string? nextToken = null;
            //var response = instance.UpdateNodeDrain(nodeId, nodeUpdateDrainRequest, region, varNamespace, index, wait, stale, prefix, xNomadToken, perPage, nextToken);
            //Assert.IsType<NodeDrainUpdateResponse>(response);
        }

        /// <summary>
        /// Test UpdateNodeEligibility
        /// </summary>
        [Fact]
        public void UpdateNodeEligibilityTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string nodeId = null;
            //NodeUpdateEligibilityRequest nodeUpdateEligibilityRequest = null;
            //string? region = null;
            //string? varNamespace = null;
            //int? index = null;
            //string? wait = null;
            //string? stale = null;
            //string? prefix = null;
            //string? xNomadToken = null;
            //int? perPage = null;
            //string? nextToken = null;
            //var response = instance.UpdateNodeEligibility(nodeId, nodeUpdateEligibilityRequest, region, varNamespace, index, wait, stale, prefix, xNomadToken, perPage, nextToken);
            //Assert.IsType<NodeEligibilityUpdateResponse>(response);
        }

        /// <summary>
        /// Test UpdateNodePurge
        /// </summary>
        [Fact]
        public void UpdateNodePurgeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string nodeId = null;
            //string? region = null;
            //string? varNamespace = null;
            //int? index = null;
            //string? wait = null;
            //string? stale = null;
            //string? prefix = null;
            //string? xNomadToken = null;
            //int? perPage = null;
            //string? nextToken = null;
            //var response = instance.UpdateNodePurge(nodeId, region, varNamespace, index, wait, stale, prefix, xNomadToken, perPage, nextToken);
            //Assert.IsType<NodePurgeResponse>(response);
        }
    }
}
