/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Fermyon.Nomad.Client;
using Fermyon.Nomad.Api;

namespace Fermyon.Nomad.Test.Api
{
    /// <summary>
    ///  Class for testing SystemApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SystemApiTests : IDisposable
    {
        private SystemApi instance;

        public SystemApiTests()
        {
            instance = new SystemApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SystemApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SystemApi
            //Assert.IsType<SystemApi>(instance);
        }

        /// <summary>
        /// Test PutSystemGC
        /// </summary>
        [Fact]
        public void PutSystemGCTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? region = null;
            //string? varNamespace = null;
            //string? xNomadToken = null;
            //string? idempotencyToken = null;
            //instance.PutSystemGC(region, varNamespace, xNomadToken, idempotencyToken);
        }

        /// <summary>
        /// Test PutSystemReconcileSummaries
        /// </summary>
        [Fact]
        public void PutSystemReconcileSummariesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? region = null;
            //string? varNamespace = null;
            //string? xNomadToken = null;
            //string? idempotencyToken = null;
            //instance.PutSystemReconcileSummaries(region, varNamespace, xNomadToken, idempotencyToken);
        }
    }
}
