/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing Affinity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AffinityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Affinity
        //private Affinity instance;

        public AffinityTests()
        {
            // TODO uncomment below to create an instance of Affinity
            //instance = new Affinity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Affinity
        /// </summary>
        [Fact]
        public void AffinityInstanceTest()
        {
            // TODO uncomment below to test "IsType" Affinity
            //Assert.IsType<Affinity>(instance);
        }


        /// <summary>
        /// Test the property 'LTarget'
        /// </summary>
        [Fact]
        public void LTargetTest()
        {
            // TODO unit test for the property 'LTarget'
        }
        /// <summary>
        /// Test the property 'Operand'
        /// </summary>
        [Fact]
        public void OperandTest()
        {
            // TODO unit test for the property 'Operand'
        }
        /// <summary>
        /// Test the property 'RTarget'
        /// </summary>
        [Fact]
        public void RTargetTest()
        {
            // TODO unit test for the property 'RTarget'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Fact]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }

    }

}
