/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing AllocatedCpuResources
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AllocatedCpuResourcesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AllocatedCpuResources
        //private AllocatedCpuResources instance;

        public AllocatedCpuResourcesTests()
        {
            // TODO uncomment below to create an instance of AllocatedCpuResources
            //instance = new AllocatedCpuResources();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AllocatedCpuResources
        /// </summary>
        [Fact]
        public void AllocatedCpuResourcesInstanceTest()
        {
            // TODO uncomment below to test "IsType" AllocatedCpuResources
            //Assert.IsType<AllocatedCpuResources>(instance);
        }


        /// <summary>
        /// Test the property 'CpuShares'
        /// </summary>
        [Fact]
        public void CpuSharesTest()
        {
            // TODO unit test for the property 'CpuShares'
        }

    }

}
