/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing AllocatedDeviceResource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AllocatedDeviceResourceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AllocatedDeviceResource
        //private AllocatedDeviceResource instance;

        public AllocatedDeviceResourceTests()
        {
            // TODO uncomment below to create an instance of AllocatedDeviceResource
            //instance = new AllocatedDeviceResource();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AllocatedDeviceResource
        /// </summary>
        [Fact]
        public void AllocatedDeviceResourceInstanceTest()
        {
            // TODO uncomment below to test "IsType" AllocatedDeviceResource
            //Assert.IsType<AllocatedDeviceResource>(instance);
        }

        /// <summary>
        /// Test the property 'DeviceIDs'
        /// </summary>
        [Fact]
        public void DeviceIDsTest()
        {
            // TODO unit test for the property 'DeviceIDs'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Vendor'
        /// </summary>
        [Fact]
        public void VendorTest()
        {
            // TODO unit test for the property 'Vendor'
        }
    }
}
