/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing AllocatedTaskResources
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AllocatedTaskResourcesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AllocatedTaskResources
        //private AllocatedTaskResources instance;

        public AllocatedTaskResourcesTests()
        {
            // TODO uncomment below to create an instance of AllocatedTaskResources
            //instance = new AllocatedTaskResources();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AllocatedTaskResources
        /// </summary>
        [Fact]
        public void AllocatedTaskResourcesInstanceTest()
        {
            // TODO uncomment below to test "IsType" AllocatedTaskResources
            //Assert.IsType<AllocatedTaskResources>(instance);
        }


        /// <summary>
        /// Test the property 'Cpu'
        /// </summary>
        [Fact]
        public void CpuTest()
        {
            // TODO unit test for the property 'Cpu'
        }
        /// <summary>
        /// Test the property 'Devices'
        /// </summary>
        [Fact]
        public void DevicesTest()
        {
            // TODO unit test for the property 'Devices'
        }
        /// <summary>
        /// Test the property 'Memory'
        /// </summary>
        [Fact]
        public void MemoryTest()
        {
            // TODO unit test for the property 'Memory'
        }
        /// <summary>
        /// Test the property 'Networks'
        /// </summary>
        [Fact]
        public void NetworksTest()
        {
            // TODO unit test for the property 'Networks'
        }

    }

}
