/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing Attribute
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AttributeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Attribute
        //private Attribute instance;

        public AttributeTests()
        {
            // TODO uncomment below to create an instance of Attribute
            //instance = new Attribute();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Attribute
        /// </summary>
        [Fact]
        public void AttributeInstanceTest()
        {
            // TODO uncomment below to test "IsType" Attribute
            //Assert.IsType<Attribute>(instance);
        }


        /// <summary>
        /// Test the property 'Bool'
        /// </summary>
        [Fact]
        public void BoolTest()
        {
            // TODO unit test for the property 'Bool'
        }
        /// <summary>
        /// Test the property 'Float'
        /// </summary>
        [Fact]
        public void FloatTest()
        {
            // TODO unit test for the property 'Float'
        }
        /// <summary>
        /// Test the property 'Int'
        /// </summary>
        [Fact]
        public void IntTest()
        {
            // TODO unit test for the property 'Int'
        }
        /// <summary>
        /// Test the property 'String'
        /// </summary>
        [Fact]
        public void StringTest()
        {
            // TODO unit test for the property 'String'
        }
        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Fact]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }

    }

}
