/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing AutopilotConfiguration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AutopilotConfigurationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AutopilotConfiguration
        //private AutopilotConfiguration instance;

        public AutopilotConfigurationTests()
        {
            // TODO uncomment below to create an instance of AutopilotConfiguration
            //instance = new AutopilotConfiguration();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AutopilotConfiguration
        /// </summary>
        [Fact]
        public void AutopilotConfigurationInstanceTest()
        {
            // TODO uncomment below to test "IsType" AutopilotConfiguration
            //Assert.IsType<AutopilotConfiguration>(instance);
        }


        /// <summary>
        /// Test the property 'CleanupDeadServers'
        /// </summary>
        [Fact]
        public void CleanupDeadServersTest()
        {
            // TODO unit test for the property 'CleanupDeadServers'
        }
        /// <summary>
        /// Test the property 'CreateIndex'
        /// </summary>
        [Fact]
        public void CreateIndexTest()
        {
            // TODO unit test for the property 'CreateIndex'
        }
        /// <summary>
        /// Test the property 'DisableUpgradeMigration'
        /// </summary>
        [Fact]
        public void DisableUpgradeMigrationTest()
        {
            // TODO unit test for the property 'DisableUpgradeMigration'
        }
        /// <summary>
        /// Test the property 'EnableCustomUpgrades'
        /// </summary>
        [Fact]
        public void EnableCustomUpgradesTest()
        {
            // TODO unit test for the property 'EnableCustomUpgrades'
        }
        /// <summary>
        /// Test the property 'EnableRedundancyZones'
        /// </summary>
        [Fact]
        public void EnableRedundancyZonesTest()
        {
            // TODO unit test for the property 'EnableRedundancyZones'
        }
        /// <summary>
        /// Test the property 'LastContactThreshold'
        /// </summary>
        [Fact]
        public void LastContactThresholdTest()
        {
            // TODO unit test for the property 'LastContactThreshold'
        }
        /// <summary>
        /// Test the property 'MaxTrailingLogs'
        /// </summary>
        [Fact]
        public void MaxTrailingLogsTest()
        {
            // TODO unit test for the property 'MaxTrailingLogs'
        }
        /// <summary>
        /// Test the property 'MinQuorum'
        /// </summary>
        [Fact]
        public void MinQuorumTest()
        {
            // TODO unit test for the property 'MinQuorum'
        }
        /// <summary>
        /// Test the property 'ModifyIndex'
        /// </summary>
        [Fact]
        public void ModifyIndexTest()
        {
            // TODO unit test for the property 'ModifyIndex'
        }
        /// <summary>
        /// Test the property 'ServerStabilizationTime'
        /// </summary>
        [Fact]
        public void ServerStabilizationTimeTest()
        {
            // TODO unit test for the property 'ServerStabilizationTime'
        }

    }

}
