/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing CheckRestart
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CheckRestartTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CheckRestart
        //private CheckRestart instance;

        public CheckRestartTests()
        {
            // TODO uncomment below to create an instance of CheckRestart
            //instance = new CheckRestart();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CheckRestart
        /// </summary>
        [Fact]
        public void CheckRestartInstanceTest()
        {
            // TODO uncomment below to test "IsType" CheckRestart
            //Assert.IsType<CheckRestart>(instance);
        }

        /// <summary>
        /// Test the property 'Grace'
        /// </summary>
        [Fact]
        public void GraceTest()
        {
            // TODO unit test for the property 'Grace'
        }

        /// <summary>
        /// Test the property 'IgnoreWarnings'
        /// </summary>
        [Fact]
        public void IgnoreWarningsTest()
        {
            // TODO unit test for the property 'IgnoreWarnings'
        }

        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Fact]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }
    }
}
