/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing ConsulGatewayProxy
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConsulGatewayProxyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConsulGatewayProxy
        //private ConsulGatewayProxy instance;

        public ConsulGatewayProxyTests()
        {
            // TODO uncomment below to create an instance of ConsulGatewayProxy
            //instance = new ConsulGatewayProxy();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConsulGatewayProxy
        /// </summary>
        [Fact]
        public void ConsulGatewayProxyInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConsulGatewayProxy
            //Assert.IsType<ConsulGatewayProxy>(instance);
        }

        /// <summary>
        /// Test the property 'Config'
        /// </summary>
        [Fact]
        public void ConfigTest()
        {
            // TODO unit test for the property 'Config'
        }

        /// <summary>
        /// Test the property 'ConnectTimeout'
        /// </summary>
        [Fact]
        public void ConnectTimeoutTest()
        {
            // TODO unit test for the property 'ConnectTimeout'
        }

        /// <summary>
        /// Test the property 'EnvoyDNSDiscoveryType'
        /// </summary>
        [Fact]
        public void EnvoyDNSDiscoveryTypeTest()
        {
            // TODO unit test for the property 'EnvoyDNSDiscoveryType'
        }

        /// <summary>
        /// Test the property 'EnvoyGatewayBindAddresses'
        /// </summary>
        [Fact]
        public void EnvoyGatewayBindAddressesTest()
        {
            // TODO unit test for the property 'EnvoyGatewayBindAddresses'
        }

        /// <summary>
        /// Test the property 'EnvoyGatewayBindTaggedAddresses'
        /// </summary>
        [Fact]
        public void EnvoyGatewayBindTaggedAddressesTest()
        {
            // TODO unit test for the property 'EnvoyGatewayBindTaggedAddresses'
        }

        /// <summary>
        /// Test the property 'EnvoyGatewayNoDefaultBind'
        /// </summary>
        [Fact]
        public void EnvoyGatewayNoDefaultBindTest()
        {
            // TODO unit test for the property 'EnvoyGatewayNoDefaultBind'
        }
    }
}
