/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing ConsulGateway
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConsulGatewayTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConsulGateway
        //private ConsulGateway instance;

        public ConsulGatewayTests()
        {
            // TODO uncomment below to create an instance of ConsulGateway
            //instance = new ConsulGateway();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConsulGateway
        /// </summary>
        [Fact]
        public void ConsulGatewayInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConsulGateway
            //Assert.IsType<ConsulGateway>(instance);
        }


        /// <summary>
        /// Test the property 'Ingress'
        /// </summary>
        [Fact]
        public void IngressTest()
        {
            // TODO unit test for the property 'Ingress'
        }
        /// <summary>
        /// Test the property 'Mesh'
        /// </summary>
        [Fact]
        public void MeshTest()
        {
            // TODO unit test for the property 'Mesh'
        }
        /// <summary>
        /// Test the property 'Proxy'
        /// </summary>
        [Fact]
        public void ProxyTest()
        {
            // TODO unit test for the property 'Proxy'
        }
        /// <summary>
        /// Test the property 'Terminating'
        /// </summary>
        [Fact]
        public void TerminatingTest()
        {
            // TODO unit test for the property 'Terminating'
        }

    }

}
