/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing ConsulTerminatingConfigEntry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConsulTerminatingConfigEntryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConsulTerminatingConfigEntry
        //private ConsulTerminatingConfigEntry instance;

        public ConsulTerminatingConfigEntryTests()
        {
            // TODO uncomment below to create an instance of ConsulTerminatingConfigEntry
            //instance = new ConsulTerminatingConfigEntry();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConsulTerminatingConfigEntry
        /// </summary>
        [Fact]
        public void ConsulTerminatingConfigEntryInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConsulTerminatingConfigEntry
            //Assert.IsType<ConsulTerminatingConfigEntry>(instance);
        }

        /// <summary>
        /// Test the property 'Services'
        /// </summary>
        [Fact]
        public void ServicesTest()
        {
            // TODO unit test for the property 'Services'
        }
    }
}
