/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing ConsulLinkedService
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConsulLinkedServiceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConsulLinkedService
        //private ConsulLinkedService instance;

        public ConsulLinkedServiceTests()
        {
            // TODO uncomment below to create an instance of ConsulLinkedService
            //instance = new ConsulLinkedService();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConsulLinkedService
        /// </summary>
        [Fact]
        public void ConsulLinkedServiceInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConsulLinkedService
            //Assert.IsType<ConsulLinkedService>(instance);
        }

        /// <summary>
        /// Test the property 'CAFile'
        /// </summary>
        [Fact]
        public void CAFileTest()
        {
            // TODO unit test for the property 'CAFile'
        }

        /// <summary>
        /// Test the property 'CertFile'
        /// </summary>
        [Fact]
        public void CertFileTest()
        {
            // TODO unit test for the property 'CertFile'
        }

        /// <summary>
        /// Test the property 'KeyFile'
        /// </summary>
        [Fact]
        public void KeyFileTest()
        {
            // TODO unit test for the property 'KeyFile'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'SNI'
        /// </summary>
        [Fact]
        public void SNITest()
        {
            // TODO unit test for the property 'SNI'
        }
    }
}
