/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing ConsulIngressListener
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConsulIngressListenerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConsulIngressListener
        //private ConsulIngressListener instance;

        public ConsulIngressListenerTests()
        {
            // TODO uncomment below to create an instance of ConsulIngressListener
            //instance = new ConsulIngressListener();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConsulIngressListener
        /// </summary>
        [Fact]
        public void ConsulIngressListenerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConsulIngressListener
            //Assert.IsType<ConsulIngressListener>(instance);
        }

        /// <summary>
        /// Test the property 'Port'
        /// </summary>
        [Fact]
        public void PortTest()
        {
            // TODO unit test for the property 'Port'
        }

        /// <summary>
        /// Test the property 'Protocol'
        /// </summary>
        [Fact]
        public void ProtocolTest()
        {
            // TODO unit test for the property 'Protocol'
        }

        /// <summary>
        /// Test the property 'Services'
        /// </summary>
        [Fact]
        public void ServicesTest()
        {
            // TODO unit test for the property 'Services'
        }
    }
}
