/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing ConsulIngressService
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConsulIngressServiceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConsulIngressService
        //private ConsulIngressService instance;

        public ConsulIngressServiceTests()
        {
            // TODO uncomment below to create an instance of ConsulIngressService
            //instance = new ConsulIngressService();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConsulIngressService
        /// </summary>
        [Fact]
        public void ConsulIngressServiceInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConsulIngressService
            //Assert.IsType<ConsulIngressService>(instance);
        }

        /// <summary>
        /// Test the property 'Hosts'
        /// </summary>
        [Fact]
        public void HostsTest()
        {
            // TODO unit test for the property 'Hosts'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
