/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing ConsulUpstream
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConsulUpstreamTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConsulUpstream
        //private ConsulUpstream instance;

        public ConsulUpstreamTests()
        {
            // TODO uncomment below to create an instance of ConsulUpstream
            //instance = new ConsulUpstream();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConsulUpstream
        /// </summary>
        [Fact]
        public void ConsulUpstreamInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConsulUpstream
            //Assert.IsType<ConsulUpstream>(instance);
        }


        /// <summary>
        /// Test the property 'Datacenter'
        /// </summary>
        [Fact]
        public void DatacenterTest()
        {
            // TODO unit test for the property 'Datacenter'
        }
        /// <summary>
        /// Test the property 'DestinationName'
        /// </summary>
        [Fact]
        public void DestinationNameTest()
        {
            // TODO unit test for the property 'DestinationName'
        }
        /// <summary>
        /// Test the property 'LocalBindAddress'
        /// </summary>
        [Fact]
        public void LocalBindAddressTest()
        {
            // TODO unit test for the property 'LocalBindAddress'
        }
        /// <summary>
        /// Test the property 'LocalBindPort'
        /// </summary>
        [Fact]
        public void LocalBindPortTest()
        {
            // TODO unit test for the property 'LocalBindPort'
        }
        /// <summary>
        /// Test the property 'MeshGateway'
        /// </summary>
        [Fact]
        public void MeshGatewayTest()
        {
            // TODO unit test for the property 'MeshGateway'
        }

    }

}
