/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing CSIInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CSIInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CSIInfo
        //private CSIInfo instance;

        public CSIInfoTests()
        {
            // TODO uncomment below to create an instance of CSIInfo
            //instance = new CSIInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CSIInfo
        /// </summary>
        [Fact]
        public void CSIInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CSIInfo
            //Assert.IsType<CSIInfo>(instance);
        }

        /// <summary>
        /// Test the property 'AllocID'
        /// </summary>
        [Fact]
        public void AllocIDTest()
        {
            // TODO unit test for the property 'AllocID'
        }

        /// <summary>
        /// Test the property 'ControllerInfo'
        /// </summary>
        [Fact]
        public void ControllerInfoTest()
        {
            // TODO unit test for the property 'ControllerInfo'
        }

        /// <summary>
        /// Test the property 'HealthDescription'
        /// </summary>
        [Fact]
        public void HealthDescriptionTest()
        {
            // TODO unit test for the property 'HealthDescription'
        }

        /// <summary>
        /// Test the property 'Healthy'
        /// </summary>
        [Fact]
        public void HealthyTest()
        {
            // TODO unit test for the property 'Healthy'
        }

        /// <summary>
        /// Test the property 'NodeInfo'
        /// </summary>
        [Fact]
        public void NodeInfoTest()
        {
            // TODO unit test for the property 'NodeInfo'
        }

        /// <summary>
        /// Test the property 'PluginID'
        /// </summary>
        [Fact]
        public void PluginIDTest()
        {
            // TODO unit test for the property 'PluginID'
        }

        /// <summary>
        /// Test the property 'RequiresControllerPlugin'
        /// </summary>
        [Fact]
        public void RequiresControllerPluginTest()
        {
            // TODO unit test for the property 'RequiresControllerPlugin'
        }

        /// <summary>
        /// Test the property 'RequiresTopologies'
        /// </summary>
        [Fact]
        public void RequiresTopologiesTest()
        {
            // TODO unit test for the property 'RequiresTopologies'
        }

        /// <summary>
        /// Test the property 'UpdateTime'
        /// </summary>
        [Fact]
        public void UpdateTimeTest()
        {
            // TODO unit test for the property 'UpdateTime'
        }
    }
}
