/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing CSIMountOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CSIMountOptionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CSIMountOptions
        //private CSIMountOptions instance;

        public CSIMountOptionsTests()
        {
            // TODO uncomment below to create an instance of CSIMountOptions
            //instance = new CSIMountOptions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CSIMountOptions
        /// </summary>
        [Fact]
        public void CSIMountOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" CSIMountOptions
            //Assert.IsType<CSIMountOptions>(instance);
        }


        /// <summary>
        /// Test the property 'FSType'
        /// </summary>
        [Fact]
        public void FSTypeTest()
        {
            // TODO unit test for the property 'FSType'
        }
        /// <summary>
        /// Test the property 'MountFlags'
        /// </summary>
        [Fact]
        public void MountFlagsTest()
        {
            // TODO unit test for the property 'MountFlags'
        }

    }

}
