/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing CSIPluginListStub
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CSIPluginListStubTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CSIPluginListStub
        //private CSIPluginListStub instance;

        public CSIPluginListStubTests()
        {
            // TODO uncomment below to create an instance of CSIPluginListStub
            //instance = new CSIPluginListStub();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CSIPluginListStub
        /// </summary>
        [Fact]
        public void CSIPluginListStubInstanceTest()
        {
            // TODO uncomment below to test "IsType" CSIPluginListStub
            //Assert.IsType<CSIPluginListStub>(instance);
        }


        /// <summary>
        /// Test the property 'ControllerRequired'
        /// </summary>
        [Fact]
        public void ControllerRequiredTest()
        {
            // TODO unit test for the property 'ControllerRequired'
        }
        /// <summary>
        /// Test the property 'ControllersExpected'
        /// </summary>
        [Fact]
        public void ControllersExpectedTest()
        {
            // TODO unit test for the property 'ControllersExpected'
        }
        /// <summary>
        /// Test the property 'ControllersHealthy'
        /// </summary>
        [Fact]
        public void ControllersHealthyTest()
        {
            // TODO unit test for the property 'ControllersHealthy'
        }
        /// <summary>
        /// Test the property 'CreateIndex'
        /// </summary>
        [Fact]
        public void CreateIndexTest()
        {
            // TODO unit test for the property 'CreateIndex'
        }
        /// <summary>
        /// Test the property 'ID'
        /// </summary>
        [Fact]
        public void IDTest()
        {
            // TODO unit test for the property 'ID'
        }
        /// <summary>
        /// Test the property 'ModifyIndex'
        /// </summary>
        [Fact]
        public void ModifyIndexTest()
        {
            // TODO unit test for the property 'ModifyIndex'
        }
        /// <summary>
        /// Test the property 'NodesExpected'
        /// </summary>
        [Fact]
        public void NodesExpectedTest()
        {
            // TODO unit test for the property 'NodesExpected'
        }
        /// <summary>
        /// Test the property 'NodesHealthy'
        /// </summary>
        [Fact]
        public void NodesHealthyTest()
        {
            // TODO unit test for the property 'NodesHealthy'
        }
        /// <summary>
        /// Test the property 'Provider'
        /// </summary>
        [Fact]
        public void ProviderTest()
        {
            // TODO unit test for the property 'Provider'
        }

    }

}
