/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing CSIVolumeListExternalResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CSIVolumeListExternalResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CSIVolumeListExternalResponse
        //private CSIVolumeListExternalResponse instance;

        public CSIVolumeListExternalResponseTests()
        {
            // TODO uncomment below to create an instance of CSIVolumeListExternalResponse
            //instance = new CSIVolumeListExternalResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CSIVolumeListExternalResponse
        /// </summary>
        [Fact]
        public void CSIVolumeListExternalResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CSIVolumeListExternalResponse
            //Assert.IsType<CSIVolumeListExternalResponse>(instance);
        }


        /// <summary>
        /// Test the property 'NextToken'
        /// </summary>
        [Fact]
        public void NextTokenTest()
        {
            // TODO unit test for the property 'NextToken'
        }
        /// <summary>
        /// Test the property 'Volumes'
        /// </summary>
        [Fact]
        public void VolumesTest()
        {
            // TODO unit test for the property 'Volumes'
        }

    }

}
