/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing DeploymentPauseRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeploymentPauseRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeploymentPauseRequest
        //private DeploymentPauseRequest instance;

        public DeploymentPauseRequestTests()
        {
            // TODO uncomment below to create an instance of DeploymentPauseRequest
            //instance = new DeploymentPauseRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeploymentPauseRequest
        /// </summary>
        [Fact]
        public void DeploymentPauseRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeploymentPauseRequest
            //Assert.IsType<DeploymentPauseRequest>(instance);
        }

        /// <summary>
        /// Test the property 'DeploymentID'
        /// </summary>
        [Fact]
        public void DeploymentIDTest()
        {
            // TODO unit test for the property 'DeploymentID'
        }

        /// <summary>
        /// Test the property 'VarNamespace'
        /// </summary>
        [Fact]
        public void VarNamespaceTest()
        {
            // TODO unit test for the property 'VarNamespace'
        }

        /// <summary>
        /// Test the property 'Pause'
        /// </summary>
        [Fact]
        public void PauseTest()
        {
            // TODO unit test for the property 'Pause'
        }

        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Fact]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }

        /// <summary>
        /// Test the property 'SecretID'
        /// </summary>
        [Fact]
        public void SecretIDTest()
        {
            // TODO unit test for the property 'SecretID'
        }
    }
}
