/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing Deployment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeploymentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Deployment
        //private Deployment instance;

        public DeploymentTests()
        {
            // TODO uncomment below to create an instance of Deployment
            //instance = new Deployment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Deployment
        /// </summary>
        [Fact]
        public void DeploymentInstanceTest()
        {
            // TODO uncomment below to test "IsType" Deployment
            //Assert.IsType<Deployment>(instance);
        }

        /// <summary>
        /// Test the property 'CreateIndex'
        /// </summary>
        [Fact]
        public void CreateIndexTest()
        {
            // TODO unit test for the property 'CreateIndex'
        }

        /// <summary>
        /// Test the property 'ID'
        /// </summary>
        [Fact]
        public void IDTest()
        {
            // TODO unit test for the property 'ID'
        }

        /// <summary>
        /// Test the property 'IsMultiregion'
        /// </summary>
        [Fact]
        public void IsMultiregionTest()
        {
            // TODO unit test for the property 'IsMultiregion'
        }

        /// <summary>
        /// Test the property 'JobCreateIndex'
        /// </summary>
        [Fact]
        public void JobCreateIndexTest()
        {
            // TODO unit test for the property 'JobCreateIndex'
        }

        /// <summary>
        /// Test the property 'JobID'
        /// </summary>
        [Fact]
        public void JobIDTest()
        {
            // TODO unit test for the property 'JobID'
        }

        /// <summary>
        /// Test the property 'JobModifyIndex'
        /// </summary>
        [Fact]
        public void JobModifyIndexTest()
        {
            // TODO unit test for the property 'JobModifyIndex'
        }

        /// <summary>
        /// Test the property 'JobSpecModifyIndex'
        /// </summary>
        [Fact]
        public void JobSpecModifyIndexTest()
        {
            // TODO unit test for the property 'JobSpecModifyIndex'
        }

        /// <summary>
        /// Test the property 'JobVersion'
        /// </summary>
        [Fact]
        public void JobVersionTest()
        {
            // TODO unit test for the property 'JobVersion'
        }

        /// <summary>
        /// Test the property 'ModifyIndex'
        /// </summary>
        [Fact]
        public void ModifyIndexTest()
        {
            // TODO unit test for the property 'ModifyIndex'
        }

        /// <summary>
        /// Test the property 'VarNamespace'
        /// </summary>
        [Fact]
        public void VarNamespaceTest()
        {
            // TODO unit test for the property 'VarNamespace'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'StatusDescription'
        /// </summary>
        [Fact]
        public void StatusDescriptionTest()
        {
            // TODO unit test for the property 'StatusDescription'
        }

        /// <summary>
        /// Test the property 'TaskGroups'
        /// </summary>
        [Fact]
        public void TaskGroupsTest()
        {
            // TODO unit test for the property 'TaskGroups'
        }
    }
}
