/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing DrainMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DrainMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DrainMetadata
        //private DrainMetadata instance;

        public DrainMetadataTests()
        {
            // TODO uncomment below to create an instance of DrainMetadata
            //instance = new DrainMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DrainMetadata
        /// </summary>
        [Fact]
        public void DrainMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" DrainMetadata
            //Assert.IsType<DrainMetadata>(instance);
        }

        /// <summary>
        /// Test the property 'AccessorID'
        /// </summary>
        [Fact]
        public void AccessorIDTest()
        {
            // TODO unit test for the property 'AccessorID'
        }

        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Fact]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }

        /// <summary>
        /// Test the property 'StartedAt'
        /// </summary>
        [Fact]
        public void StartedAtTest()
        {
            // TODO unit test for the property 'StartedAt'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
