/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing DriverInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DriverInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DriverInfo
        //private DriverInfo instance;

        public DriverInfoTests()
        {
            // TODO uncomment below to create an instance of DriverInfo
            //instance = new DriverInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DriverInfo
        /// </summary>
        [Fact]
        public void DriverInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" DriverInfo
            //Assert.IsType<DriverInfo>(instance);
        }

        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }

        /// <summary>
        /// Test the property 'Detected'
        /// </summary>
        [Fact]
        public void DetectedTest()
        {
            // TODO unit test for the property 'Detected'
        }

        /// <summary>
        /// Test the property 'HealthDescription'
        /// </summary>
        [Fact]
        public void HealthDescriptionTest()
        {
            // TODO unit test for the property 'HealthDescription'
        }

        /// <summary>
        /// Test the property 'Healthy'
        /// </summary>
        [Fact]
        public void HealthyTest()
        {
            // TODO unit test for the property 'Healthy'
        }

        /// <summary>
        /// Test the property 'UpdateTime'
        /// </summary>
        [Fact]
        public void UpdateTimeTest()
        {
            // TODO unit test for the property 'UpdateTime'
        }
    }
}
