/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing EvaluationStub
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EvaluationStubTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EvaluationStub
        //private EvaluationStub instance;

        public EvaluationStubTests()
        {
            // TODO uncomment below to create an instance of EvaluationStub
            //instance = new EvaluationStub();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EvaluationStub
        /// </summary>
        [Fact]
        public void EvaluationStubInstanceTest()
        {
            // TODO uncomment below to test "IsType" EvaluationStub
            //Assert.IsType<EvaluationStub>(instance);
        }


        /// <summary>
        /// Test the property 'BlockedEval'
        /// </summary>
        [Fact]
        public void BlockedEvalTest()
        {
            // TODO unit test for the property 'BlockedEval'
        }
        /// <summary>
        /// Test the property 'CreateIndex'
        /// </summary>
        [Fact]
        public void CreateIndexTest()
        {
            // TODO unit test for the property 'CreateIndex'
        }
        /// <summary>
        /// Test the property 'CreateTime'
        /// </summary>
        [Fact]
        public void CreateTimeTest()
        {
            // TODO unit test for the property 'CreateTime'
        }
        /// <summary>
        /// Test the property 'DeploymentID'
        /// </summary>
        [Fact]
        public void DeploymentIDTest()
        {
            // TODO unit test for the property 'DeploymentID'
        }
        /// <summary>
        /// Test the property 'ID'
        /// </summary>
        [Fact]
        public void IDTest()
        {
            // TODO unit test for the property 'ID'
        }
        /// <summary>
        /// Test the property 'JobID'
        /// </summary>
        [Fact]
        public void JobIDTest()
        {
            // TODO unit test for the property 'JobID'
        }
        /// <summary>
        /// Test the property 'ModifyIndex'
        /// </summary>
        [Fact]
        public void ModifyIndexTest()
        {
            // TODO unit test for the property 'ModifyIndex'
        }
        /// <summary>
        /// Test the property 'ModifyTime'
        /// </summary>
        [Fact]
        public void ModifyTimeTest()
        {
            // TODO unit test for the property 'ModifyTime'
        }
        /// <summary>
        /// Test the property 'Namespace'
        /// </summary>
        [Fact]
        public void NamespaceTest()
        {
            // TODO unit test for the property 'Namespace'
        }
        /// <summary>
        /// Test the property 'NextEval'
        /// </summary>
        [Fact]
        public void NextEvalTest()
        {
            // TODO unit test for the property 'NextEval'
        }
        /// <summary>
        /// Test the property 'NodeID'
        /// </summary>
        [Fact]
        public void NodeIDTest()
        {
            // TODO unit test for the property 'NodeID'
        }
        /// <summary>
        /// Test the property 'PreviousEval'
        /// </summary>
        [Fact]
        public void PreviousEvalTest()
        {
            // TODO unit test for the property 'PreviousEval'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Fact]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StatusDescription'
        /// </summary>
        [Fact]
        public void StatusDescriptionTest()
        {
            // TODO unit test for the property 'StatusDescription'
        }
        /// <summary>
        /// Test the property 'TriggeredBy'
        /// </summary>
        [Fact]
        public void TriggeredByTest()
        {
            // TODO unit test for the property 'TriggeredBy'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'WaitUntil'
        /// </summary>
        [Fact]
        public void WaitUntilTest()
        {
            // TODO unit test for the property 'WaitUntil'
        }

    }

}
