/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing HostVolumeInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HostVolumeInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HostVolumeInfo
        //private HostVolumeInfo instance;

        public HostVolumeInfoTests()
        {
            // TODO uncomment below to create an instance of HostVolumeInfo
            //instance = new HostVolumeInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HostVolumeInfo
        /// </summary>
        [Fact]
        public void HostVolumeInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" HostVolumeInfo
            //Assert.IsType<HostVolumeInfo>(instance);
        }

        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }

        /// <summary>
        /// Test the property 'VarReadOnly'
        /// </summary>
        [Fact]
        public void VarReadOnlyTest()
        {
            // TODO unit test for the property 'VarReadOnly'
        }
    }
}
