/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing JobDispatchRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobDispatchRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JobDispatchRequest
        //private JobDispatchRequest instance;

        public JobDispatchRequestTests()
        {
            // TODO uncomment below to create an instance of JobDispatchRequest
            //instance = new JobDispatchRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobDispatchRequest
        /// </summary>
        [Fact]
        public void JobDispatchRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" JobDispatchRequest
            //Assert.IsType<JobDispatchRequest>(instance);
        }


        /// <summary>
        /// Test the property 'JobID'
        /// </summary>
        [Fact]
        public void JobIDTest()
        {
            // TODO unit test for the property 'JobID'
        }
        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Fact]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }
        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }

    }

}
