/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing JobPlanRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobPlanRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JobPlanRequest
        //private JobPlanRequest instance;

        public JobPlanRequestTests()
        {
            // TODO uncomment below to create an instance of JobPlanRequest
            //instance = new JobPlanRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobPlanRequest
        /// </summary>
        [Fact]
        public void JobPlanRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" JobPlanRequest
            //Assert.IsType<JobPlanRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Diff'
        /// </summary>
        [Fact]
        public void DiffTest()
        {
            // TODO unit test for the property 'Diff'
        }
        /// <summary>
        /// Test the property 'Job'
        /// </summary>
        [Fact]
        public void JobTest()
        {
            // TODO unit test for the property 'Job'
        }
        /// <summary>
        /// Test the property 'Namespace'
        /// </summary>
        [Fact]
        public void NamespaceTest()
        {
            // TODO unit test for the property 'Namespace'
        }
        /// <summary>
        /// Test the property 'PolicyOverride'
        /// </summary>
        [Fact]
        public void PolicyOverrideTest()
        {
            // TODO unit test for the property 'PolicyOverride'
        }
        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Fact]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'SecretID'
        /// </summary>
        [Fact]
        public void SecretIDTest()
        {
            // TODO unit test for the property 'SecretID'
        }

    }

}
