/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing JobRegisterRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobRegisterRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JobRegisterRequest
        //private JobRegisterRequest instance;

        public JobRegisterRequestTests()
        {
            // TODO uncomment below to create an instance of JobRegisterRequest
            //instance = new JobRegisterRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobRegisterRequest
        /// </summary>
        [Fact]
        public void JobRegisterRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" JobRegisterRequest
            //Assert.IsType<JobRegisterRequest>(instance);
        }


        /// <summary>
        /// Test the property 'EnforceIndex'
        /// </summary>
        [Fact]
        public void EnforceIndexTest()
        {
            // TODO unit test for the property 'EnforceIndex'
        }
        /// <summary>
        /// Test the property 'EvalPriority'
        /// </summary>
        [Fact]
        public void EvalPriorityTest()
        {
            // TODO unit test for the property 'EvalPriority'
        }
        /// <summary>
        /// Test the property 'Job'
        /// </summary>
        [Fact]
        public void JobTest()
        {
            // TODO unit test for the property 'Job'
        }
        /// <summary>
        /// Test the property 'JobModifyIndex'
        /// </summary>
        [Fact]
        public void JobModifyIndexTest()
        {
            // TODO unit test for the property 'JobModifyIndex'
        }
        /// <summary>
        /// Test the property 'Namespace'
        /// </summary>
        [Fact]
        public void NamespaceTest()
        {
            // TODO unit test for the property 'Namespace'
        }
        /// <summary>
        /// Test the property 'PolicyOverride'
        /// </summary>
        [Fact]
        public void PolicyOverrideTest()
        {
            // TODO unit test for the property 'PolicyOverride'
        }
        /// <summary>
        /// Test the property 'PreserveCounts'
        /// </summary>
        [Fact]
        public void PreserveCountsTest()
        {
            // TODO unit test for the property 'PreserveCounts'
        }
        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Fact]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'SecretID'
        /// </summary>
        [Fact]
        public void SecretIDTest()
        {
            // TODO unit test for the property 'SecretID'
        }

    }

}
