/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing JobsParseRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobsParseRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JobsParseRequest
        //private JobsParseRequest instance;

        public JobsParseRequestTests()
        {
            // TODO uncomment below to create an instance of JobsParseRequest
            //instance = new JobsParseRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobsParseRequest
        /// </summary>
        [Fact]
        public void JobsParseRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" JobsParseRequest
            //Assert.IsType<JobsParseRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Canonicalize'
        /// </summary>
        [Fact]
        public void CanonicalizeTest()
        {
            // TODO unit test for the property 'Canonicalize'
        }
        /// <summary>
        /// Test the property 'JobHCL'
        /// </summary>
        [Fact]
        public void JobHCLTest()
        {
            // TODO unit test for the property 'JobHCL'
        }
        /// <summary>
        /// Test the property 'Hclv1'
        /// </summary>
        [Fact]
        public void Hclv1Test()
        {
            // TODO unit test for the property 'Hclv1'
        }

    }

}
