/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing JobStabilityResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobStabilityResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JobStabilityResponse
        //private JobStabilityResponse instance;

        public JobStabilityResponseTests()
        {
            // TODO uncomment below to create an instance of JobStabilityResponse
            //instance = new JobStabilityResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobStabilityResponse
        /// </summary>
        [Fact]
        public void JobStabilityResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" JobStabilityResponse
            //Assert.IsType<JobStabilityResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
    }
}
