/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing Job
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Job
        //private Job instance;

        public JobTests()
        {
            // TODO uncomment below to create an instance of Job
            //instance = new Job();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Job
        /// </summary>
        [Fact]
        public void JobInstanceTest()
        {
            // TODO uncomment below to test "IsType" Job
            //Assert.IsType<Job>(instance);
        }

        /// <summary>
        /// Test the property 'Affinities'
        /// </summary>
        [Fact]
        public void AffinitiesTest()
        {
            // TODO unit test for the property 'Affinities'
        }

        /// <summary>
        /// Test the property 'AllAtOnce'
        /// </summary>
        [Fact]
        public void AllAtOnceTest()
        {
            // TODO unit test for the property 'AllAtOnce'
        }

        /// <summary>
        /// Test the property 'Constraints'
        /// </summary>
        [Fact]
        public void ConstraintsTest()
        {
            // TODO unit test for the property 'Constraints'
        }

        /// <summary>
        /// Test the property 'ConsulNamespace'
        /// </summary>
        [Fact]
        public void ConsulNamespaceTest()
        {
            // TODO unit test for the property 'ConsulNamespace'
        }

        /// <summary>
        /// Test the property 'ConsulToken'
        /// </summary>
        [Fact]
        public void ConsulTokenTest()
        {
            // TODO unit test for the property 'ConsulToken'
        }

        /// <summary>
        /// Test the property 'CreateIndex'
        /// </summary>
        [Fact]
        public void CreateIndexTest()
        {
            // TODO unit test for the property 'CreateIndex'
        }

        /// <summary>
        /// Test the property 'Datacenters'
        /// </summary>
        [Fact]
        public void DatacentersTest()
        {
            // TODO unit test for the property 'Datacenters'
        }

        /// <summary>
        /// Test the property 'DispatchIdempotencyToken'
        /// </summary>
        [Fact]
        public void DispatchIdempotencyTokenTest()
        {
            // TODO unit test for the property 'DispatchIdempotencyToken'
        }

        /// <summary>
        /// Test the property 'Dispatched'
        /// </summary>
        [Fact]
        public void DispatchedTest()
        {
            // TODO unit test for the property 'Dispatched'
        }

        /// <summary>
        /// Test the property 'ID'
        /// </summary>
        [Fact]
        public void IDTest()
        {
            // TODO unit test for the property 'ID'
        }

        /// <summary>
        /// Test the property 'JobModifyIndex'
        /// </summary>
        [Fact]
        public void JobModifyIndexTest()
        {
            // TODO unit test for the property 'JobModifyIndex'
        }

        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Fact]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }

        /// <summary>
        /// Test the property 'Migrate'
        /// </summary>
        [Fact]
        public void MigrateTest()
        {
            // TODO unit test for the property 'Migrate'
        }

        /// <summary>
        /// Test the property 'ModifyIndex'
        /// </summary>
        [Fact]
        public void ModifyIndexTest()
        {
            // TODO unit test for the property 'ModifyIndex'
        }

        /// <summary>
        /// Test the property 'Multiregion'
        /// </summary>
        [Fact]
        public void MultiregionTest()
        {
            // TODO unit test for the property 'Multiregion'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'VarNamespace'
        /// </summary>
        [Fact]
        public void VarNamespaceTest()
        {
            // TODO unit test for the property 'VarNamespace'
        }

        /// <summary>
        /// Test the property 'NomadTokenID'
        /// </summary>
        [Fact]
        public void NomadTokenIDTest()
        {
            // TODO unit test for the property 'NomadTokenID'
        }

        /// <summary>
        /// Test the property 'ParameterizedJob'
        /// </summary>
        [Fact]
        public void ParameterizedJobTest()
        {
            // TODO unit test for the property 'ParameterizedJob'
        }

        /// <summary>
        /// Test the property 'ParentID'
        /// </summary>
        [Fact]
        public void ParentIDTest()
        {
            // TODO unit test for the property 'ParentID'
        }

        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }

        /// <summary>
        /// Test the property 'Periodic'
        /// </summary>
        [Fact]
        public void PeriodicTest()
        {
            // TODO unit test for the property 'Periodic'
        }

        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Fact]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }

        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Fact]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }

        /// <summary>
        /// Test the property 'Reschedule'
        /// </summary>
        [Fact]
        public void RescheduleTest()
        {
            // TODO unit test for the property 'Reschedule'
        }

        /// <summary>
        /// Test the property 'Spreads'
        /// </summary>
        [Fact]
        public void SpreadsTest()
        {
            // TODO unit test for the property 'Spreads'
        }

        /// <summary>
        /// Test the property 'Stable'
        /// </summary>
        [Fact]
        public void StableTest()
        {
            // TODO unit test for the property 'Stable'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'StatusDescription'
        /// </summary>
        [Fact]
        public void StatusDescriptionTest()
        {
            // TODO unit test for the property 'StatusDescription'
        }

        /// <summary>
        /// Test the property 'Stop'
        /// </summary>
        [Fact]
        public void StopTest()
        {
            // TODO unit test for the property 'Stop'
        }

        /// <summary>
        /// Test the property 'SubmitTime'
        /// </summary>
        [Fact]
        public void SubmitTimeTest()
        {
            // TODO unit test for the property 'SubmitTime'
        }

        /// <summary>
        /// Test the property 'TaskGroups'
        /// </summary>
        [Fact]
        public void TaskGroupsTest()
        {
            // TODO unit test for the property 'TaskGroups'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Update'
        /// </summary>
        [Fact]
        public void UpdateTest()
        {
            // TODO unit test for the property 'Update'
        }

        /// <summary>
        /// Test the property 'VaultNamespace'
        /// </summary>
        [Fact]
        public void VaultNamespaceTest()
        {
            // TODO unit test for the property 'VaultNamespace'
        }

        /// <summary>
        /// Test the property 'VaultToken'
        /// </summary>
        [Fact]
        public void VaultTokenTest()
        {
            // TODO unit test for the property 'VaultToken'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }
    }
}
