/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing NetworkResource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NetworkResourceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NetworkResource
        //private NetworkResource instance;

        public NetworkResourceTests()
        {
            // TODO uncomment below to create an instance of NetworkResource
            //instance = new NetworkResource();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NetworkResource
        /// </summary>
        [Fact]
        public void NetworkResourceInstanceTest()
        {
            // TODO uncomment below to test "IsType" NetworkResource
            //Assert.IsType<NetworkResource>(instance);
        }

        /// <summary>
        /// Test the property 'CIDR'
        /// </summary>
        [Fact]
        public void CIDRTest()
        {
            // TODO unit test for the property 'CIDR'
        }

        /// <summary>
        /// Test the property 'DNS'
        /// </summary>
        [Fact]
        public void DNSTest()
        {
            // TODO unit test for the property 'DNS'
        }

        /// <summary>
        /// Test the property 'Device'
        /// </summary>
        [Fact]
        public void DeviceTest()
        {
            // TODO unit test for the property 'Device'
        }

        /// <summary>
        /// Test the property 'DynamicPorts'
        /// </summary>
        [Fact]
        public void DynamicPortsTest()
        {
            // TODO unit test for the property 'DynamicPorts'
        }

        /// <summary>
        /// Test the property 'Hostname'
        /// </summary>
        [Fact]
        public void HostnameTest()
        {
            // TODO unit test for the property 'Hostname'
        }

        /// <summary>
        /// Test the property 'IP'
        /// </summary>
        [Fact]
        public void IPTest()
        {
            // TODO unit test for the property 'IP'
        }

        /// <summary>
        /// Test the property 'MBits'
        /// </summary>
        [Fact]
        public void MBitsTest()
        {
            // TODO unit test for the property 'MBits'
        }

        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Fact]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }

        /// <summary>
        /// Test the property 'ReservedPorts'
        /// </summary>
        [Fact]
        public void ReservedPortsTest()
        {
            // TODO unit test for the property 'ReservedPorts'
        }
    }
}
