/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing NodeMemoryResources
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NodeMemoryResourcesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NodeMemoryResources
        //private NodeMemoryResources instance;

        public NodeMemoryResourcesTests()
        {
            // TODO uncomment below to create an instance of NodeMemoryResources
            //instance = new NodeMemoryResources();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NodeMemoryResources
        /// </summary>
        [Fact]
        public void NodeMemoryResourcesInstanceTest()
        {
            // TODO uncomment below to test "IsType" NodeMemoryResources
            //Assert.IsType<NodeMemoryResources>(instance);
        }


        /// <summary>
        /// Test the property 'MemoryMB'
        /// </summary>
        [Fact]
        public void MemoryMBTest()
        {
            // TODO unit test for the property 'MemoryMB'
        }

    }

}
