/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing NodeUpdateDrainRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NodeUpdateDrainRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NodeUpdateDrainRequest
        //private NodeUpdateDrainRequest instance;

        public NodeUpdateDrainRequestTests()
        {
            // TODO uncomment below to create an instance of NodeUpdateDrainRequest
            //instance = new NodeUpdateDrainRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NodeUpdateDrainRequest
        /// </summary>
        [Fact]
        public void NodeUpdateDrainRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" NodeUpdateDrainRequest
            //Assert.IsType<NodeUpdateDrainRequest>(instance);
        }


        /// <summary>
        /// Test the property 'DrainSpec'
        /// </summary>
        [Fact]
        public void DrainSpecTest()
        {
            // TODO unit test for the property 'DrainSpec'
        }
        /// <summary>
        /// Test the property 'MarkEligible'
        /// </summary>
        [Fact]
        public void MarkEligibleTest()
        {
            // TODO unit test for the property 'MarkEligible'
        }
        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Fact]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }
        /// <summary>
        /// Test the property 'NodeID'
        /// </summary>
        [Fact]
        public void NodeIDTest()
        {
            // TODO unit test for the property 'NodeID'
        }

    }

}
