/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing NodeUpdateEligibilityRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NodeUpdateEligibilityRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NodeUpdateEligibilityRequest
        //private NodeUpdateEligibilityRequest instance;

        public NodeUpdateEligibilityRequestTests()
        {
            // TODO uncomment below to create an instance of NodeUpdateEligibilityRequest
            //instance = new NodeUpdateEligibilityRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NodeUpdateEligibilityRequest
        /// </summary>
        [Fact]
        public void NodeUpdateEligibilityRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" NodeUpdateEligibilityRequest
            //Assert.IsType<NodeUpdateEligibilityRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Eligibility'
        /// </summary>
        [Fact]
        public void EligibilityTest()
        {
            // TODO unit test for the property 'Eligibility'
        }

        /// <summary>
        /// Test the property 'NodeID'
        /// </summary>
        [Fact]
        public void NodeIDTest()
        {
            // TODO unit test for the property 'NodeID'
        }
    }
}
