/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing NodeReservedNetworkResources
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NodeReservedNetworkResourcesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NodeReservedNetworkResources
        //private NodeReservedNetworkResources instance;

        public NodeReservedNetworkResourcesTests()
        {
            // TODO uncomment below to create an instance of NodeReservedNetworkResources
            //instance = new NodeReservedNetworkResources();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NodeReservedNetworkResources
        /// </summary>
        [Fact]
        public void NodeReservedNetworkResourcesInstanceTest()
        {
            // TODO uncomment below to test "IsType" NodeReservedNetworkResources
            //Assert.IsType<NodeReservedNetworkResources>(instance);
        }

        /// <summary>
        /// Test the property 'ReservedHostPorts'
        /// </summary>
        [Fact]
        public void ReservedHostPortsTest()
        {
            // TODO unit test for the property 'ReservedHostPorts'
        }
    }
}
