/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing NodeDrainUpdateResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NodeDrainUpdateResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NodeDrainUpdateResponse
        //private NodeDrainUpdateResponse instance;

        public NodeDrainUpdateResponseTests()
        {
            // TODO uncomment below to create an instance of NodeDrainUpdateResponse
            //instance = new NodeDrainUpdateResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NodeDrainUpdateResponse
        /// </summary>
        [Fact]
        public void NodeDrainUpdateResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" NodeDrainUpdateResponse
            //Assert.IsType<NodeDrainUpdateResponse>(instance);
        }

        /// <summary>
        /// Test the property 'EvalCreateIndex'
        /// </summary>
        [Fact]
        public void EvalCreateIndexTest()
        {
            // TODO unit test for the property 'EvalCreateIndex'
        }

        /// <summary>
        /// Test the property 'EvalIDs'
        /// </summary>
        [Fact]
        public void EvalIDsTest()
        {
            // TODO unit test for the property 'EvalIDs'
        }

        /// <summary>
        /// Test the property 'LastIndex'
        /// </summary>
        [Fact]
        public void LastIndexTest()
        {
            // TODO unit test for the property 'LastIndex'
        }

        /// <summary>
        /// Test the property 'NodeModifyIndex'
        /// </summary>
        [Fact]
        public void NodeModifyIndexTest()
        {
            // TODO unit test for the property 'NodeModifyIndex'
        }

        /// <summary>
        /// Test the property 'RequestTime'
        /// </summary>
        [Fact]
        public void RequestTimeTest()
        {
            // TODO unit test for the property 'RequestTime'
        }
    }
}
