/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing Node
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NodeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Node
        //private Node instance;

        public NodeTests()
        {
            // TODO uncomment below to create an instance of Node
            //instance = new Node();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Node
        /// </summary>
        [Fact]
        public void NodeInstanceTest()
        {
            // TODO uncomment below to test "IsType" Node
            //Assert.IsType<Node>(instance);
        }


        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
        /// <summary>
        /// Test the property 'CSIControllerPlugins'
        /// </summary>
        [Fact]
        public void CSIControllerPluginsTest()
        {
            // TODO unit test for the property 'CSIControllerPlugins'
        }
        /// <summary>
        /// Test the property 'CSINodePlugins'
        /// </summary>
        [Fact]
        public void CSINodePluginsTest()
        {
            // TODO unit test for the property 'CSINodePlugins'
        }
        /// <summary>
        /// Test the property 'CgroupParent'
        /// </summary>
        [Fact]
        public void CgroupParentTest()
        {
            // TODO unit test for the property 'CgroupParent'
        }
        /// <summary>
        /// Test the property 'CreateIndex'
        /// </summary>
        [Fact]
        public void CreateIndexTest()
        {
            // TODO unit test for the property 'CreateIndex'
        }
        /// <summary>
        /// Test the property 'Datacenter'
        /// </summary>
        [Fact]
        public void DatacenterTest()
        {
            // TODO unit test for the property 'Datacenter'
        }
        /// <summary>
        /// Test the property 'Drain'
        /// </summary>
        [Fact]
        public void DrainTest()
        {
            // TODO unit test for the property 'Drain'
        }
        /// <summary>
        /// Test the property 'DrainStrategy'
        /// </summary>
        [Fact]
        public void DrainStrategyTest()
        {
            // TODO unit test for the property 'DrainStrategy'
        }
        /// <summary>
        /// Test the property 'Drivers'
        /// </summary>
        [Fact]
        public void DriversTest()
        {
            // TODO unit test for the property 'Drivers'
        }
        /// <summary>
        /// Test the property 'Events'
        /// </summary>
        [Fact]
        public void EventsTest()
        {
            // TODO unit test for the property 'Events'
        }
        /// <summary>
        /// Test the property 'HTTPAddr'
        /// </summary>
        [Fact]
        public void HTTPAddrTest()
        {
            // TODO unit test for the property 'HTTPAddr'
        }
        /// <summary>
        /// Test the property 'HostNetworks'
        /// </summary>
        [Fact]
        public void HostNetworksTest()
        {
            // TODO unit test for the property 'HostNetworks'
        }
        /// <summary>
        /// Test the property 'HostVolumes'
        /// </summary>
        [Fact]
        public void HostVolumesTest()
        {
            // TODO unit test for the property 'HostVolumes'
        }
        /// <summary>
        /// Test the property 'ID'
        /// </summary>
        [Fact]
        public void IDTest()
        {
            // TODO unit test for the property 'ID'
        }
        /// <summary>
        /// Test the property 'LastDrain'
        /// </summary>
        [Fact]
        public void LastDrainTest()
        {
            // TODO unit test for the property 'LastDrain'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Fact]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }
        /// <summary>
        /// Test the property 'ModifyIndex'
        /// </summary>
        [Fact]
        public void ModifyIndexTest()
        {
            // TODO unit test for the property 'ModifyIndex'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'NodeClass'
        /// </summary>
        [Fact]
        public void NodeClassTest()
        {
            // TODO unit test for the property 'NodeClass'
        }
        /// <summary>
        /// Test the property 'NodeResources'
        /// </summary>
        [Fact]
        public void NodeResourcesTest()
        {
            // TODO unit test for the property 'NodeResources'
        }
        /// <summary>
        /// Test the property 'Reserved'
        /// </summary>
        [Fact]
        public void ReservedTest()
        {
            // TODO unit test for the property 'Reserved'
        }
        /// <summary>
        /// Test the property 'ReservedResources'
        /// </summary>
        [Fact]
        public void ReservedResourcesTest()
        {
            // TODO unit test for the property 'ReservedResources'
        }
        /// <summary>
        /// Test the property 'Resources'
        /// </summary>
        [Fact]
        public void ResourcesTest()
        {
            // TODO unit test for the property 'Resources'
        }
        /// <summary>
        /// Test the property 'SchedulingEligibility'
        /// </summary>
        [Fact]
        public void SchedulingEligibilityTest()
        {
            // TODO unit test for the property 'SchedulingEligibility'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StatusDescription'
        /// </summary>
        [Fact]
        public void StatusDescriptionTest()
        {
            // TODO unit test for the property 'StatusDescription'
        }
        /// <summary>
        /// Test the property 'StatusUpdatedAt'
        /// </summary>
        [Fact]
        public void StatusUpdatedAtTest()
        {
            // TODO unit test for the property 'StatusUpdatedAt'
        }
        /// <summary>
        /// Test the property 'TLSEnabled'
        /// </summary>
        [Fact]
        public void TLSEnabledTest()
        {
            // TODO unit test for the property 'TLSEnabled'
        }

    }

}
