/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing NodeCpuResources
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NodeCpuResourcesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NodeCpuResources
        //private NodeCpuResources instance;

        public NodeCpuResourcesTests()
        {
            // TODO uncomment below to create an instance of NodeCpuResources
            //instance = new NodeCpuResources();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NodeCpuResources
        /// </summary>
        [Fact]
        public void NodeCpuResourcesInstanceTest()
        {
            // TODO uncomment below to test "IsType" NodeCpuResources
            //Assert.IsType<NodeCpuResources>(instance);
        }


        /// <summary>
        /// Test the property 'CpuShares'
        /// </summary>
        [Fact]
        public void CpuSharesTest()
        {
            // TODO unit test for the property 'CpuShares'
        }
        /// <summary>
        /// Test the property 'ReservableCpuCores'
        /// </summary>
        [Fact]
        public void ReservableCpuCoresTest()
        {
            // TODO unit test for the property 'ReservableCpuCores'
        }
        /// <summary>
        /// Test the property 'TotalCpuCores'
        /// </summary>
        [Fact]
        public void TotalCpuCoresTest()
        {
            // TODO unit test for the property 'TotalCpuCores'
        }

    }

}
