/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing NodeReservedMemoryResources
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NodeReservedMemoryResourcesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NodeReservedMemoryResources
        //private NodeReservedMemoryResources instance;

        public NodeReservedMemoryResourcesTests()
        {
            // TODO uncomment below to create an instance of NodeReservedMemoryResources
            //instance = new NodeReservedMemoryResources();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NodeReservedMemoryResources
        /// </summary>
        [Fact]
        public void NodeReservedMemoryResourcesInstanceTest()
        {
            // TODO uncomment below to test "IsType" NodeReservedMemoryResources
            //Assert.IsType<NodeReservedMemoryResources>(instance);
        }


        /// <summary>
        /// Test the property 'MemoryMB'
        /// </summary>
        [Fact]
        public void MemoryMBTest()
        {
            // TODO unit test for the property 'MemoryMB'
        }

    }

}
