/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing OneTimeTokenExchangeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OneTimeTokenExchangeRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OneTimeTokenExchangeRequest
        //private OneTimeTokenExchangeRequest instance;

        public OneTimeTokenExchangeRequestTests()
        {
            // TODO uncomment below to create an instance of OneTimeTokenExchangeRequest
            //instance = new OneTimeTokenExchangeRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OneTimeTokenExchangeRequest
        /// </summary>
        [Fact]
        public void OneTimeTokenExchangeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OneTimeTokenExchangeRequest
            //Assert.IsType<OneTimeTokenExchangeRequest>(instance);
        }

        /// <summary>
        /// Test the property 'OneTimeSecretID'
        /// </summary>
        [Fact]
        public void OneTimeSecretIDTest()
        {
            // TODO unit test for the property 'OneTimeSecretID'
        }
    }
}
