/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing ParameterizedJobConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParameterizedJobConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ParameterizedJobConfig
        //private ParameterizedJobConfig instance;

        public ParameterizedJobConfigTests()
        {
            // TODO uncomment below to create an instance of ParameterizedJobConfig
            //instance = new ParameterizedJobConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ParameterizedJobConfig
        /// </summary>
        [Fact]
        public void ParameterizedJobConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" ParameterizedJobConfig
            //Assert.IsType<ParameterizedJobConfig>(instance);
        }

        /// <summary>
        /// Test the property 'MetaOptional'
        /// </summary>
        [Fact]
        public void MetaOptionalTest()
        {
            // TODO unit test for the property 'MetaOptional'
        }

        /// <summary>
        /// Test the property 'MetaRequired'
        /// </summary>
        [Fact]
        public void MetaRequiredTest()
        {
            // TODO unit test for the property 'MetaRequired'
        }

        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }
    }
}
