/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing PreemptionConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PreemptionConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PreemptionConfig
        //private PreemptionConfig instance;

        public PreemptionConfigTests()
        {
            // TODO uncomment below to create an instance of PreemptionConfig
            //instance = new PreemptionConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PreemptionConfig
        /// </summary>
        [Fact]
        public void PreemptionConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" PreemptionConfig
            //Assert.IsType<PreemptionConfig>(instance);
        }

        /// <summary>
        /// Test the property 'BatchSchedulerEnabled'
        /// </summary>
        [Fact]
        public void BatchSchedulerEnabledTest()
        {
            // TODO unit test for the property 'BatchSchedulerEnabled'
        }

        /// <summary>
        /// Test the property 'ServiceSchedulerEnabled'
        /// </summary>
        [Fact]
        public void ServiceSchedulerEnabledTest()
        {
            // TODO unit test for the property 'ServiceSchedulerEnabled'
        }

        /// <summary>
        /// Test the property 'SysBatchSchedulerEnabled'
        /// </summary>
        [Fact]
        public void SysBatchSchedulerEnabledTest()
        {
            // TODO unit test for the property 'SysBatchSchedulerEnabled'
        }

        /// <summary>
        /// Test the property 'SystemSchedulerEnabled'
        /// </summary>
        [Fact]
        public void SystemSchedulerEnabledTest()
        {
            // TODO unit test for the property 'SystemSchedulerEnabled'
        }
    }
}
