/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing QuotaLimit
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QuotaLimitTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QuotaLimit
        //private QuotaLimit instance;

        public QuotaLimitTests()
        {
            // TODO uncomment below to create an instance of QuotaLimit
            //instance = new QuotaLimit();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QuotaLimit
        /// </summary>
        [Fact]
        public void QuotaLimitInstanceTest()
        {
            // TODO uncomment below to test "IsType" QuotaLimit
            //Assert.IsType<QuotaLimit>(instance);
        }

        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Fact]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }

        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Fact]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }

        /// <summary>
        /// Test the property 'RegionLimit'
        /// </summary>
        [Fact]
        public void RegionLimitTest()
        {
            // TODO unit test for the property 'RegionLimit'
        }
    }
}
