/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing RaftServer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RaftServerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RaftServer
        //private RaftServer instance;

        public RaftServerTests()
        {
            // TODO uncomment below to create an instance of RaftServer
            //instance = new RaftServer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RaftServer
        /// </summary>
        [Fact]
        public void RaftServerInstanceTest()
        {
            // TODO uncomment below to test "IsType" RaftServer
            //Assert.IsType<RaftServer>(instance);
        }


        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'ID'
        /// </summary>
        [Fact]
        public void IDTest()
        {
            // TODO unit test for the property 'ID'
        }
        /// <summary>
        /// Test the property 'Leader'
        /// </summary>
        [Fact]
        public void LeaderTest()
        {
            // TODO unit test for the property 'Leader'
        }
        /// <summary>
        /// Test the property 'Node'
        /// </summary>
        [Fact]
        public void NodeTest()
        {
            // TODO unit test for the property 'Node'
        }
        /// <summary>
        /// Test the property 'RaftProtocol'
        /// </summary>
        [Fact]
        public void RaftProtocolTest()
        {
            // TODO unit test for the property 'RaftProtocol'
        }
        /// <summary>
        /// Test the property 'Voter'
        /// </summary>
        [Fact]
        public void VoterTest()
        {
            // TODO unit test for the property 'Voter'
        }

    }

}
