/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing ReschedulePolicy
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReschedulePolicyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReschedulePolicy
        //private ReschedulePolicy instance;

        public ReschedulePolicyTests()
        {
            // TODO uncomment below to create an instance of ReschedulePolicy
            //instance = new ReschedulePolicy();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReschedulePolicy
        /// </summary>
        [Fact]
        public void ReschedulePolicyInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReschedulePolicy
            //Assert.IsType<ReschedulePolicy>(instance);
        }

        /// <summary>
        /// Test the property 'Attempts'
        /// </summary>
        [Fact]
        public void AttemptsTest()
        {
            // TODO unit test for the property 'Attempts'
        }

        /// <summary>
        /// Test the property 'Delay'
        /// </summary>
        [Fact]
        public void DelayTest()
        {
            // TODO unit test for the property 'Delay'
        }

        /// <summary>
        /// Test the property 'DelayFunction'
        /// </summary>
        [Fact]
        public void DelayFunctionTest()
        {
            // TODO unit test for the property 'DelayFunction'
        }

        /// <summary>
        /// Test the property 'Interval'
        /// </summary>
        [Fact]
        public void IntervalTest()
        {
            // TODO unit test for the property 'Interval'
        }

        /// <summary>
        /// Test the property 'MaxDelay'
        /// </summary>
        [Fact]
        public void MaxDelayTest()
        {
            // TODO unit test for the property 'MaxDelay'
        }

        /// <summary>
        /// Test the property 'Unlimited'
        /// </summary>
        [Fact]
        public void UnlimitedTest()
        {
            // TODO unit test for the property 'Unlimited'
        }
    }
}
