/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing Resources
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResourcesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Resources
        //private Resources instance;

        public ResourcesTests()
        {
            // TODO uncomment below to create an instance of Resources
            //instance = new Resources();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Resources
        /// </summary>
        [Fact]
        public void ResourcesInstanceTest()
        {
            // TODO uncomment below to test "IsType" Resources
            //Assert.IsType<Resources>(instance);
        }


        /// <summary>
        /// Test the property 'CPU'
        /// </summary>
        [Fact]
        public void CPUTest()
        {
            // TODO unit test for the property 'CPU'
        }
        /// <summary>
        /// Test the property 'Cores'
        /// </summary>
        [Fact]
        public void CoresTest()
        {
            // TODO unit test for the property 'Cores'
        }
        /// <summary>
        /// Test the property 'Devices'
        /// </summary>
        [Fact]
        public void DevicesTest()
        {
            // TODO unit test for the property 'Devices'
        }
        /// <summary>
        /// Test the property 'DiskMB'
        /// </summary>
        [Fact]
        public void DiskMBTest()
        {
            // TODO unit test for the property 'DiskMB'
        }
        /// <summary>
        /// Test the property 'IOPS'
        /// </summary>
        [Fact]
        public void IOPSTest()
        {
            // TODO unit test for the property 'IOPS'
        }
        /// <summary>
        /// Test the property 'MemoryMB'
        /// </summary>
        [Fact]
        public void MemoryMBTest()
        {
            // TODO unit test for the property 'MemoryMB'
        }
        /// <summary>
        /// Test the property 'MemoryMaxMB'
        /// </summary>
        [Fact]
        public void MemoryMaxMBTest()
        {
            // TODO unit test for the property 'MemoryMaxMB'
        }
        /// <summary>
        /// Test the property 'Networks'
        /// </summary>
        [Fact]
        public void NetworksTest()
        {
            // TODO unit test for the property 'Networks'
        }

    }

}
