/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing RestartPolicy
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RestartPolicyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RestartPolicy
        //private RestartPolicy instance;

        public RestartPolicyTests()
        {
            // TODO uncomment below to create an instance of RestartPolicy
            //instance = new RestartPolicy();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RestartPolicy
        /// </summary>
        [Fact]
        public void RestartPolicyInstanceTest()
        {
            // TODO uncomment below to test "IsType" RestartPolicy
            //Assert.IsType<RestartPolicy>(instance);
        }


        /// <summary>
        /// Test the property 'Attempts'
        /// </summary>
        [Fact]
        public void AttemptsTest()
        {
            // TODO unit test for the property 'Attempts'
        }
        /// <summary>
        /// Test the property 'Delay'
        /// </summary>
        [Fact]
        public void DelayTest()
        {
            // TODO unit test for the property 'Delay'
        }
        /// <summary>
        /// Test the property 'Interval'
        /// </summary>
        [Fact]
        public void IntervalTest()
        {
            // TODO unit test for the property 'Interval'
        }
        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Fact]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }

    }

}
