/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing SchedulerConfigurationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SchedulerConfigurationResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SchedulerConfigurationResponse
        //private SchedulerConfigurationResponse instance;

        public SchedulerConfigurationResponseTests()
        {
            // TODO uncomment below to create an instance of SchedulerConfigurationResponse
            //instance = new SchedulerConfigurationResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SchedulerConfigurationResponse
        /// </summary>
        [Fact]
        public void SchedulerConfigurationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SchedulerConfigurationResponse
            //Assert.IsType<SchedulerConfigurationResponse>(instance);
        }

        /// <summary>
        /// Test the property 'KnownLeader'
        /// </summary>
        [Fact]
        public void KnownLeaderTest()
        {
            // TODO unit test for the property 'KnownLeader'
        }

        /// <summary>
        /// Test the property 'LastContact'
        /// </summary>
        [Fact]
        public void LastContactTest()
        {
            // TODO unit test for the property 'LastContact'
        }

        /// <summary>
        /// Test the property 'LastIndex'
        /// </summary>
        [Fact]
        public void LastIndexTest()
        {
            // TODO unit test for the property 'LastIndex'
        }

        /// <summary>
        /// Test the property 'NextToken'
        /// </summary>
        [Fact]
        public void NextTokenTest()
        {
            // TODO unit test for the property 'NextToken'
        }

        /// <summary>
        /// Test the property 'RequestTime'
        /// </summary>
        [Fact]
        public void RequestTimeTest()
        {
            // TODO unit test for the property 'RequestTime'
        }

        /// <summary>
        /// Test the property 'SchedulerConfig'
        /// </summary>
        [Fact]
        public void SchedulerConfigTest()
        {
            // TODO unit test for the property 'SchedulerConfig'
        }
    }
}
