/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing SchedulerSetConfigurationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SchedulerSetConfigurationResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SchedulerSetConfigurationResponse
        //private SchedulerSetConfigurationResponse instance;

        public SchedulerSetConfigurationResponseTests()
        {
            // TODO uncomment below to create an instance of SchedulerSetConfigurationResponse
            //instance = new SchedulerSetConfigurationResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SchedulerSetConfigurationResponse
        /// </summary>
        [Fact]
        public void SchedulerSetConfigurationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SchedulerSetConfigurationResponse
            //Assert.IsType<SchedulerSetConfigurationResponse>(instance);
        }


        /// <summary>
        /// Test the property 'LastIndex'
        /// </summary>
        [Fact]
        public void LastIndexTest()
        {
            // TODO unit test for the property 'LastIndex'
        }
        /// <summary>
        /// Test the property 'RequestTime'
        /// </summary>
        [Fact]
        public void RequestTimeTest()
        {
            // TODO unit test for the property 'RequestTime'
        }
        /// <summary>
        /// Test the property 'Updated'
        /// </summary>
        [Fact]
        public void UpdatedTest()
        {
            // TODO unit test for the property 'Updated'
        }

    }

}
