/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceCheck
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceCheckTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceCheck
        //private ServiceCheck instance;

        public ServiceCheckTests()
        {
            // TODO uncomment below to create an instance of ServiceCheck
            //instance = new ServiceCheck();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceCheck
        /// </summary>
        [Fact]
        public void ServiceCheckInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceCheck
            //Assert.IsType<ServiceCheck>(instance);
        }


        /// <summary>
        /// Test the property 'AddressMode'
        /// </summary>
        [Fact]
        public void AddressModeTest()
        {
            // TODO unit test for the property 'AddressMode'
        }
        /// <summary>
        /// Test the property 'Args'
        /// </summary>
        [Fact]
        public void ArgsTest()
        {
            // TODO unit test for the property 'Args'
        }
        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Fact]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }
        /// <summary>
        /// Test the property 'CheckRestart'
        /// </summary>
        [Fact]
        public void CheckRestartTest()
        {
            // TODO unit test for the property 'CheckRestart'
        }
        /// <summary>
        /// Test the property 'Command'
        /// </summary>
        [Fact]
        public void CommandTest()
        {
            // TODO unit test for the property 'Command'
        }
        /// <summary>
        /// Test the property 'Expose'
        /// </summary>
        [Fact]
        public void ExposeTest()
        {
            // TODO unit test for the property 'Expose'
        }
        /// <summary>
        /// Test the property 'FailuresBeforeCritical'
        /// </summary>
        [Fact]
        public void FailuresBeforeCriticalTest()
        {
            // TODO unit test for the property 'FailuresBeforeCritical'
        }
        /// <summary>
        /// Test the property 'GRPCService'
        /// </summary>
        [Fact]
        public void GRPCServiceTest()
        {
            // TODO unit test for the property 'GRPCService'
        }
        /// <summary>
        /// Test the property 'GRPCUseTLS'
        /// </summary>
        [Fact]
        public void GRPCUseTLSTest()
        {
            // TODO unit test for the property 'GRPCUseTLS'
        }
        /// <summary>
        /// Test the property 'Header'
        /// </summary>
        [Fact]
        public void HeaderTest()
        {
            // TODO unit test for the property 'Header'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'InitialStatus'
        /// </summary>
        [Fact]
        public void InitialStatusTest()
        {
            // TODO unit test for the property 'InitialStatus'
        }
        /// <summary>
        /// Test the property 'Interval'
        /// </summary>
        [Fact]
        public void IntervalTest()
        {
            // TODO unit test for the property 'Interval'
        }
        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'OnUpdate'
        /// </summary>
        [Fact]
        public void OnUpdateTest()
        {
            // TODO unit test for the property 'OnUpdate'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'PortLabel'
        /// </summary>
        [Fact]
        public void PortLabelTest()
        {
            // TODO unit test for the property 'PortLabel'
        }
        /// <summary>
        /// Test the property 'Protocol'
        /// </summary>
        [Fact]
        public void ProtocolTest()
        {
            // TODO unit test for the property 'Protocol'
        }
        /// <summary>
        /// Test the property 'SuccessBeforePassing'
        /// </summary>
        [Fact]
        public void SuccessBeforePassingTest()
        {
            // TODO unit test for the property 'SuccessBeforePassing'
        }
        /// <summary>
        /// Test the property 'TLSSkipVerify'
        /// </summary>
        [Fact]
        public void TLSSkipVerifyTest()
        {
            // TODO unit test for the property 'TLSSkipVerify'
        }
        /// <summary>
        /// Test the property 'TaskName'
        /// </summary>
        [Fact]
        public void TaskNameTest()
        {
            // TODO unit test for the property 'TaskName'
        }
        /// <summary>
        /// Test the property 'Timeout'
        /// </summary>
        [Fact]
        public void TimeoutTest()
        {
            // TODO unit test for the property 'Timeout'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
