/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing Service
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Service
        //private Service instance;

        public ServiceTests()
        {
            // TODO uncomment below to create an instance of Service
            //instance = new Service();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Service
        /// </summary>
        [Fact]
        public void ServiceInstanceTest()
        {
            // TODO uncomment below to test "IsType" Service
            //Assert.IsType<Service>(instance);
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'AddressMode'
        /// </summary>
        [Fact]
        public void AddressModeTest()
        {
            // TODO unit test for the property 'AddressMode'
        }

        /// <summary>
        /// Test the property 'CanaryMeta'
        /// </summary>
        [Fact]
        public void CanaryMetaTest()
        {
            // TODO unit test for the property 'CanaryMeta'
        }

        /// <summary>
        /// Test the property 'CanaryTags'
        /// </summary>
        [Fact]
        public void CanaryTagsTest()
        {
            // TODO unit test for the property 'CanaryTags'
        }

        /// <summary>
        /// Test the property 'CheckRestart'
        /// </summary>
        [Fact]
        public void CheckRestartTest()
        {
            // TODO unit test for the property 'CheckRestart'
        }

        /// <summary>
        /// Test the property 'Checks'
        /// </summary>
        [Fact]
        public void ChecksTest()
        {
            // TODO unit test for the property 'Checks'
        }

        /// <summary>
        /// Test the property 'Connect'
        /// </summary>
        [Fact]
        public void ConnectTest()
        {
            // TODO unit test for the property 'Connect'
        }

        /// <summary>
        /// Test the property 'EnableTagOverride'
        /// </summary>
        [Fact]
        public void EnableTagOverrideTest()
        {
            // TODO unit test for the property 'EnableTagOverride'
        }

        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Fact]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'OnUpdate'
        /// </summary>
        [Fact]
        public void OnUpdateTest()
        {
            // TODO unit test for the property 'OnUpdate'
        }

        /// <summary>
        /// Test the property 'PortLabel'
        /// </summary>
        [Fact]
        public void PortLabelTest()
        {
            // TODO unit test for the property 'PortLabel'
        }

        /// <summary>
        /// Test the property 'Provider'
        /// </summary>
        [Fact]
        public void ProviderTest()
        {
            // TODO unit test for the property 'Provider'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

        /// <summary>
        /// Test the property 'TaskName'
        /// </summary>
        [Fact]
        public void TaskNameTest()
        {
            // TODO unit test for the property 'TaskName'
        }
    }
}
