/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceRegistration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceRegistrationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceRegistration
        //private ServiceRegistration instance;

        public ServiceRegistrationTests()
        {
            // TODO uncomment below to create an instance of ServiceRegistration
            //instance = new ServiceRegistration();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceRegistration
        /// </summary>
        [Fact]
        public void ServiceRegistrationInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceRegistration
            //Assert.IsType<ServiceRegistration>(instance);
        }


        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'AllocID'
        /// </summary>
        [Fact]
        public void AllocIDTest()
        {
            // TODO unit test for the property 'AllocID'
        }
        /// <summary>
        /// Test the property 'CreateIndex'
        /// </summary>
        [Fact]
        public void CreateIndexTest()
        {
            // TODO unit test for the property 'CreateIndex'
        }
        /// <summary>
        /// Test the property 'Datacenter'
        /// </summary>
        [Fact]
        public void DatacenterTest()
        {
            // TODO unit test for the property 'Datacenter'
        }
        /// <summary>
        /// Test the property 'ID'
        /// </summary>
        [Fact]
        public void IDTest()
        {
            // TODO unit test for the property 'ID'
        }
        /// <summary>
        /// Test the property 'JobID'
        /// </summary>
        [Fact]
        public void JobIDTest()
        {
            // TODO unit test for the property 'JobID'
        }
        /// <summary>
        /// Test the property 'ModifyIndex'
        /// </summary>
        [Fact]
        public void ModifyIndexTest()
        {
            // TODO unit test for the property 'ModifyIndex'
        }
        /// <summary>
        /// Test the property 'Namespace'
        /// </summary>
        [Fact]
        public void NamespaceTest()
        {
            // TODO unit test for the property 'Namespace'
        }
        /// <summary>
        /// Test the property 'NodeID'
        /// </summary>
        [Fact]
        public void NodeIDTest()
        {
            // TODO unit test for the property 'NodeID'
        }
        /// <summary>
        /// Test the property 'Port'
        /// </summary>
        [Fact]
        public void PortTest()
        {
            // TODO unit test for the property 'Port'
        }
        /// <summary>
        /// Test the property 'ServiceName'
        /// </summary>
        [Fact]
        public void ServiceNameTest()
        {
            // TODO unit test for the property 'ServiceName'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

    }

}
