/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing SidecarTask
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SidecarTaskTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SidecarTask
        //private SidecarTask instance;

        public SidecarTaskTests()
        {
            // TODO uncomment below to create an instance of SidecarTask
            //instance = new SidecarTask();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SidecarTask
        /// </summary>
        [Fact]
        public void SidecarTaskInstanceTest()
        {
            // TODO uncomment below to test "IsType" SidecarTask
            //Assert.IsType<SidecarTask>(instance);
        }

        /// <summary>
        /// Test the property 'Config'
        /// </summary>
        [Fact]
        public void ConfigTest()
        {
            // TODO unit test for the property 'Config'
        }

        /// <summary>
        /// Test the property 'Driver'
        /// </summary>
        [Fact]
        public void DriverTest()
        {
            // TODO unit test for the property 'Driver'
        }

        /// <summary>
        /// Test the property 'Env'
        /// </summary>
        [Fact]
        public void EnvTest()
        {
            // TODO unit test for the property 'Env'
        }

        /// <summary>
        /// Test the property 'KillSignal'
        /// </summary>
        [Fact]
        public void KillSignalTest()
        {
            // TODO unit test for the property 'KillSignal'
        }

        /// <summary>
        /// Test the property 'KillTimeout'
        /// </summary>
        [Fact]
        public void KillTimeoutTest()
        {
            // TODO unit test for the property 'KillTimeout'
        }

        /// <summary>
        /// Test the property 'LogConfig'
        /// </summary>
        [Fact]
        public void LogConfigTest()
        {
            // TODO unit test for the property 'LogConfig'
        }

        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Fact]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Resources'
        /// </summary>
        [Fact]
        public void ResourcesTest()
        {
            // TODO unit test for the property 'Resources'
        }

        /// <summary>
        /// Test the property 'ShutdownDelay'
        /// </summary>
        [Fact]
        public void ShutdownDelayTest()
        {
            // TODO unit test for the property 'ShutdownDelay'
        }

        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
    }
}
