/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing SpreadTarget
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SpreadTargetTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SpreadTarget
        //private SpreadTarget instance;

        public SpreadTargetTests()
        {
            // TODO uncomment below to create an instance of SpreadTarget
            //instance = new SpreadTarget();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SpreadTarget
        /// </summary>
        [Fact]
        public void SpreadTargetInstanceTest()
        {
            // TODO uncomment below to test "IsType" SpreadTarget
            //Assert.IsType<SpreadTarget>(instance);
        }

        /// <summary>
        /// Test the property 'Percent'
        /// </summary>
        [Fact]
        public void PercentTest()
        {
            // TODO unit test for the property 'Percent'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
    }
}
