/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing Spread
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SpreadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Spread
        //private Spread instance;

        public SpreadTests()
        {
            // TODO uncomment below to create an instance of Spread
            //instance = new Spread();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Spread
        /// </summary>
        [Fact]
        public void SpreadInstanceTest()
        {
            // TODO uncomment below to test "IsType" Spread
            //Assert.IsType<Spread>(instance);
        }

        /// <summary>
        /// Test the property 'Attribute'
        /// </summary>
        [Fact]
        public void AttributeTest()
        {
            // TODO unit test for the property 'Attribute'
        }

        /// <summary>
        /// Test the property 'SpreadTarget'
        /// </summary>
        [Fact]
        public void SpreadTargetTest()
        {
            // TODO unit test for the property 'SpreadTarget'
        }

        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Fact]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
    }
}
