/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing TaskGroupDiff
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaskGroupDiffTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TaskGroupDiff
        //private TaskGroupDiff instance;

        public TaskGroupDiffTests()
        {
            // TODO uncomment below to create an instance of TaskGroupDiff
            //instance = new TaskGroupDiff();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TaskGroupDiff
        /// </summary>
        [Fact]
        public void TaskGroupDiffInstanceTest()
        {
            // TODO uncomment below to test "IsType" TaskGroupDiff
            //Assert.IsType<TaskGroupDiff>(instance);
        }

        /// <summary>
        /// Test the property 'Fields'
        /// </summary>
        [Fact]
        public void FieldsTest()
        {
            // TODO unit test for the property 'Fields'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Objects'
        /// </summary>
        [Fact]
        public void ObjectsTest()
        {
            // TODO unit test for the property 'Objects'
        }

        /// <summary>
        /// Test the property 'Tasks'
        /// </summary>
        [Fact]
        public void TasksTest()
        {
            // TODO unit test for the property 'Tasks'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Updates'
        /// </summary>
        [Fact]
        public void UpdatesTest()
        {
            // TODO unit test for the property 'Updates'
        }
    }
}
