/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing Task
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaskTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Task
        //private Task instance;

        public TaskTests()
        {
            // TODO uncomment below to create an instance of Task
            //instance = new Task();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Task
        /// </summary>
        [Fact]
        public void TaskInstanceTest()
        {
            // TODO uncomment below to test "IsType" Task
            //Assert.IsType<Task>(instance);
        }


        /// <summary>
        /// Test the property 'Affinities'
        /// </summary>
        [Fact]
        public void AffinitiesTest()
        {
            // TODO unit test for the property 'Affinities'
        }
        /// <summary>
        /// Test the property 'Artifacts'
        /// </summary>
        [Fact]
        public void ArtifactsTest()
        {
            // TODO unit test for the property 'Artifacts'
        }
        /// <summary>
        /// Test the property 'CSIPluginConfig'
        /// </summary>
        [Fact]
        public void CSIPluginConfigTest()
        {
            // TODO unit test for the property 'CSIPluginConfig'
        }
        /// <summary>
        /// Test the property 'Config'
        /// </summary>
        [Fact]
        public void ConfigTest()
        {
            // TODO unit test for the property 'Config'
        }
        /// <summary>
        /// Test the property 'Constraints'
        /// </summary>
        [Fact]
        public void ConstraintsTest()
        {
            // TODO unit test for the property 'Constraints'
        }
        /// <summary>
        /// Test the property 'DispatchPayload'
        /// </summary>
        [Fact]
        public void DispatchPayloadTest()
        {
            // TODO unit test for the property 'DispatchPayload'
        }
        /// <summary>
        /// Test the property 'Driver'
        /// </summary>
        [Fact]
        public void DriverTest()
        {
            // TODO unit test for the property 'Driver'
        }
        /// <summary>
        /// Test the property 'Env'
        /// </summary>
        [Fact]
        public void EnvTest()
        {
            // TODO unit test for the property 'Env'
        }
        /// <summary>
        /// Test the property 'KillSignal'
        /// </summary>
        [Fact]
        public void KillSignalTest()
        {
            // TODO unit test for the property 'KillSignal'
        }
        /// <summary>
        /// Test the property 'KillTimeout'
        /// </summary>
        [Fact]
        public void KillTimeoutTest()
        {
            // TODO unit test for the property 'KillTimeout'
        }
        /// <summary>
        /// Test the property 'Kind'
        /// </summary>
        [Fact]
        public void KindTest()
        {
            // TODO unit test for the property 'Kind'
        }
        /// <summary>
        /// Test the property 'Leader'
        /// </summary>
        [Fact]
        public void LeaderTest()
        {
            // TODO unit test for the property 'Leader'
        }
        /// <summary>
        /// Test the property 'Lifecycle'
        /// </summary>
        [Fact]
        public void LifecycleTest()
        {
            // TODO unit test for the property 'Lifecycle'
        }
        /// <summary>
        /// Test the property 'LogConfig'
        /// </summary>
        [Fact]
        public void LogConfigTest()
        {
            // TODO unit test for the property 'LogConfig'
        }
        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Fact]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Resources'
        /// </summary>
        [Fact]
        public void ResourcesTest()
        {
            // TODO unit test for the property 'Resources'
        }
        /// <summary>
        /// Test the property 'RestartPolicy'
        /// </summary>
        [Fact]
        public void RestartPolicyTest()
        {
            // TODO unit test for the property 'RestartPolicy'
        }
        /// <summary>
        /// Test the property 'ScalingPolicies'
        /// </summary>
        [Fact]
        public void ScalingPoliciesTest()
        {
            // TODO unit test for the property 'ScalingPolicies'
        }
        /// <summary>
        /// Test the property 'Services'
        /// </summary>
        [Fact]
        public void ServicesTest()
        {
            // TODO unit test for the property 'Services'
        }
        /// <summary>
        /// Test the property 'ShutdownDelay'
        /// </summary>
        [Fact]
        public void ShutdownDelayTest()
        {
            // TODO unit test for the property 'ShutdownDelay'
        }
        /// <summary>
        /// Test the property 'Templates'
        /// </summary>
        [Fact]
        public void TemplatesTest()
        {
            // TODO unit test for the property 'Templates'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'Vault'
        /// </summary>
        [Fact]
        public void VaultTest()
        {
            // TODO unit test for the property 'Vault'
        }
        /// <summary>
        /// Test the property 'VolumeMounts'
        /// </summary>
        [Fact]
        public void VolumeMountsTest()
        {
            // TODO unit test for the property 'VolumeMounts'
        }

    }

}
