/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing TaskArtifact
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaskArtifactTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TaskArtifact
        //private TaskArtifact instance;

        public TaskArtifactTests()
        {
            // TODO uncomment below to create an instance of TaskArtifact
            //instance = new TaskArtifact();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TaskArtifact
        /// </summary>
        [Fact]
        public void TaskArtifactInstanceTest()
        {
            // TODO uncomment below to test "IsType" TaskArtifact
            //Assert.IsType<TaskArtifact>(instance);
        }


        /// <summary>
        /// Test the property 'GetterHeaders'
        /// </summary>
        [Fact]
        public void GetterHeadersTest()
        {
            // TODO unit test for the property 'GetterHeaders'
        }
        /// <summary>
        /// Test the property 'GetterMode'
        /// </summary>
        [Fact]
        public void GetterModeTest()
        {
            // TODO unit test for the property 'GetterMode'
        }
        /// <summary>
        /// Test the property 'GetterOptions'
        /// </summary>
        [Fact]
        public void GetterOptionsTest()
        {
            // TODO unit test for the property 'GetterOptions'
        }
        /// <summary>
        /// Test the property 'GetterSource'
        /// </summary>
        [Fact]
        public void GetterSourceTest()
        {
            // TODO unit test for the property 'GetterSource'
        }
        /// <summary>
        /// Test the property 'RelativeDest'
        /// </summary>
        [Fact]
        public void RelativeDestTest()
        {
            // TODO unit test for the property 'RelativeDest'
        }

    }

}
