/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing TaskLifecycle
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaskLifecycleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TaskLifecycle
        //private TaskLifecycle instance;

        public TaskLifecycleTests()
        {
            // TODO uncomment below to create an instance of TaskLifecycle
            //instance = new TaskLifecycle();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TaskLifecycle
        /// </summary>
        [Fact]
        public void TaskLifecycleInstanceTest()
        {
            // TODO uncomment below to test "IsType" TaskLifecycle
            //Assert.IsType<TaskLifecycle>(instance);
        }

        /// <summary>
        /// Test the property 'Hook'
        /// </summary>
        [Fact]
        public void HookTest()
        {
            // TODO unit test for the property 'Hook'
        }

        /// <summary>
        /// Test the property 'Sidecar'
        /// </summary>
        [Fact]
        public void SidecarTest()
        {
            // TODO unit test for the property 'Sidecar'
        }
    }
}
