/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing TaskGroupScaleStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaskGroupScaleStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TaskGroupScaleStatus
        //private TaskGroupScaleStatus instance;

        public TaskGroupScaleStatusTests()
        {
            // TODO uncomment below to create an instance of TaskGroupScaleStatus
            //instance = new TaskGroupScaleStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TaskGroupScaleStatus
        /// </summary>
        [Fact]
        public void TaskGroupScaleStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" TaskGroupScaleStatus
            //Assert.IsType<TaskGroupScaleStatus>(instance);
        }


        /// <summary>
        /// Test the property 'Desired'
        /// </summary>
        [Fact]
        public void DesiredTest()
        {
            // TODO unit test for the property 'Desired'
        }
        /// <summary>
        /// Test the property 'Events'
        /// </summary>
        [Fact]
        public void EventsTest()
        {
            // TODO unit test for the property 'Events'
        }
        /// <summary>
        /// Test the property 'Healthy'
        /// </summary>
        [Fact]
        public void HealthyTest()
        {
            // TODO unit test for the property 'Healthy'
        }
        /// <summary>
        /// Test the property 'Placed'
        /// </summary>
        [Fact]
        public void PlacedTest()
        {
            // TODO unit test for the property 'Placed'
        }
        /// <summary>
        /// Test the property 'Running'
        /// </summary>
        [Fact]
        public void RunningTest()
        {
            // TODO unit test for the property 'Running'
        }
        /// <summary>
        /// Test the property 'Unhealthy'
        /// </summary>
        [Fact]
        public void UnhealthyTest()
        {
            // TODO unit test for the property 'Unhealthy'
        }

    }

}
