/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing TaskCSIPluginConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaskCSIPluginConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TaskCSIPluginConfig
        //private TaskCSIPluginConfig instance;

        public TaskCSIPluginConfigTests()
        {
            // TODO uncomment below to create an instance of TaskCSIPluginConfig
            //instance = new TaskCSIPluginConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TaskCSIPluginConfig
        /// </summary>
        [Fact]
        public void TaskCSIPluginConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" TaskCSIPluginConfig
            //Assert.IsType<TaskCSIPluginConfig>(instance);
        }

        /// <summary>
        /// Test the property 'ID'
        /// </summary>
        [Fact]
        public void IDTest()
        {
            // TODO unit test for the property 'ID'
        }

        /// <summary>
        /// Test the property 'MountDir'
        /// </summary>
        [Fact]
        public void MountDirTest()
        {
            // TODO unit test for the property 'MountDir'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
