/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing TaskHandle
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaskHandleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TaskHandle
        //private TaskHandle instance;

        public TaskHandleTests()
        {
            // TODO uncomment below to create an instance of TaskHandle
            //instance = new TaskHandle();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TaskHandle
        /// </summary>
        [Fact]
        public void TaskHandleInstanceTest()
        {
            // TODO uncomment below to test "IsType" TaskHandle
            //Assert.IsType<TaskHandle>(instance);
        }

        /// <summary>
        /// Test the property 'DriverState'
        /// </summary>
        [Fact]
        public void DriverStateTest()
        {
            // TODO unit test for the property 'DriverState'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }
    }
}
