/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing Template
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Template
        //private Template instance;

        public TemplateTests()
        {
            // TODO uncomment below to create an instance of Template
            //instance = new Template();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Template
        /// </summary>
        [Fact]
        public void TemplateInstanceTest()
        {
            // TODO uncomment below to test "IsType" Template
            //Assert.IsType<Template>(instance);
        }


        /// <summary>
        /// Test the property 'ChangeMode'
        /// </summary>
        [Fact]
        public void ChangeModeTest()
        {
            // TODO unit test for the property 'ChangeMode'
        }
        /// <summary>
        /// Test the property 'ChangeSignal'
        /// </summary>
        [Fact]
        public void ChangeSignalTest()
        {
            // TODO unit test for the property 'ChangeSignal'
        }
        /// <summary>
        /// Test the property 'DestPath'
        /// </summary>
        [Fact]
        public void DestPathTest()
        {
            // TODO unit test for the property 'DestPath'
        }
        /// <summary>
        /// Test the property 'EmbeddedTmpl'
        /// </summary>
        [Fact]
        public void EmbeddedTmplTest()
        {
            // TODO unit test for the property 'EmbeddedTmpl'
        }
        /// <summary>
        /// Test the property 'Envvars'
        /// </summary>
        [Fact]
        public void EnvvarsTest()
        {
            // TODO unit test for the property 'Envvars'
        }
        /// <summary>
        /// Test the property 'LeftDelim'
        /// </summary>
        [Fact]
        public void LeftDelimTest()
        {
            // TODO unit test for the property 'LeftDelim'
        }
        /// <summary>
        /// Test the property 'Perms'
        /// </summary>
        [Fact]
        public void PermsTest()
        {
            // TODO unit test for the property 'Perms'
        }
        /// <summary>
        /// Test the property 'RightDelim'
        /// </summary>
        [Fact]
        public void RightDelimTest()
        {
            // TODO unit test for the property 'RightDelim'
        }
        /// <summary>
        /// Test the property 'SourcePath'
        /// </summary>
        [Fact]
        public void SourcePathTest()
        {
            // TODO unit test for the property 'SourcePath'
        }
        /// <summary>
        /// Test the property 'Splay'
        /// </summary>
        [Fact]
        public void SplayTest()
        {
            // TODO unit test for the property 'Splay'
        }
        /// <summary>
        /// Test the property 'VaultGrace'
        /// </summary>
        [Fact]
        public void VaultGraceTest()
        {
            // TODO unit test for the property 'VaultGrace'
        }
        /// <summary>
        /// Test the property 'Wait'
        /// </summary>
        [Fact]
        public void WaitTest()
        {
            // TODO unit test for the property 'Wait'
        }

    }

}
