/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateStrategy
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateStrategyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateStrategy
        //private UpdateStrategy instance;

        public UpdateStrategyTests()
        {
            // TODO uncomment below to create an instance of UpdateStrategy
            //instance = new UpdateStrategy();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateStrategy
        /// </summary>
        [Fact]
        public void UpdateStrategyInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateStrategy
            //Assert.IsType<UpdateStrategy>(instance);
        }


        /// <summary>
        /// Test the property 'AutoPromote'
        /// </summary>
        [Fact]
        public void AutoPromoteTest()
        {
            // TODO unit test for the property 'AutoPromote'
        }
        /// <summary>
        /// Test the property 'AutoRevert'
        /// </summary>
        [Fact]
        public void AutoRevertTest()
        {
            // TODO unit test for the property 'AutoRevert'
        }
        /// <summary>
        /// Test the property 'Canary'
        /// </summary>
        [Fact]
        public void CanaryTest()
        {
            // TODO unit test for the property 'Canary'
        }
        /// <summary>
        /// Test the property 'HealthCheck'
        /// </summary>
        [Fact]
        public void HealthCheckTest()
        {
            // TODO unit test for the property 'HealthCheck'
        }
        /// <summary>
        /// Test the property 'HealthyDeadline'
        /// </summary>
        [Fact]
        public void HealthyDeadlineTest()
        {
            // TODO unit test for the property 'HealthyDeadline'
        }
        /// <summary>
        /// Test the property 'MaxParallel'
        /// </summary>
        [Fact]
        public void MaxParallelTest()
        {
            // TODO unit test for the property 'MaxParallel'
        }
        /// <summary>
        /// Test the property 'MinHealthyTime'
        /// </summary>
        [Fact]
        public void MinHealthyTimeTest()
        {
            // TODO unit test for the property 'MinHealthyTime'
        }
        /// <summary>
        /// Test the property 'ProgressDeadline'
        /// </summary>
        [Fact]
        public void ProgressDeadlineTest()
        {
            // TODO unit test for the property 'ProgressDeadline'
        }
        /// <summary>
        /// Test the property 'Stagger'
        /// </summary>
        [Fact]
        public void StaggerTest()
        {
            // TODO unit test for the property 'Stagger'
        }

    }

}
