/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Fermyon.Nomad.Api;
using Fermyon.Nomad.Model;
using Fermyon.Nomad.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Fermyon.Nomad.Test.Model
{
    /// <summary>
    ///  Class for testing VolumeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VolumeRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VolumeRequest
        //private VolumeRequest instance;

        public VolumeRequestTests()
        {
            // TODO uncomment below to create an instance of VolumeRequest
            //instance = new VolumeRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VolumeRequest
        /// </summary>
        [Fact]
        public void VolumeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" VolumeRequest
            //Assert.IsType<VolumeRequest>(instance);
        }


        /// <summary>
        /// Test the property 'AccessMode'
        /// </summary>
        [Fact]
        public void AccessModeTest()
        {
            // TODO unit test for the property 'AccessMode'
        }
        /// <summary>
        /// Test the property 'AttachmentMode'
        /// </summary>
        [Fact]
        public void AttachmentModeTest()
        {
            // TODO unit test for the property 'AttachmentMode'
        }
        /// <summary>
        /// Test the property 'MountOptions'
        /// </summary>
        [Fact]
        public void MountOptionsTest()
        {
            // TODO unit test for the property 'MountOptions'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'PerAlloc'
        /// </summary>
        [Fact]
        public void PerAllocTest()
        {
            // TODO unit test for the property 'PerAlloc'
        }
        /// <summary>
        /// Test the property 'ReadOnly'
        /// </summary>
        [Fact]
        public void ReadOnlyTest()
        {
            // TODO unit test for the property 'ReadOnly'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
